// packages/react/src/Loader/Loader.tsx
import type { CSSProperties } from 'react';
import { getUiCoreConfig } from '@mszczygiel-projects/ui-core-foundations';
import './Loader.css';

/**
 * Inline spinner indicating a pending asynchronous operation.
 *
 * @example
 * <Loader size="small" label="Loading results" />
 */
export interface LoaderProps {
  /**
   * Spinner diameter.
   * @default 'default'
   */
  size?: 'small' | 'default' | 'large';
  /**
   * Accessible name announced by screen readers.
   * @default 'Loading'
   */
  label?: string;
  /** Extra class names appended to the root element. */
  className?: string;
  /** Inline styles forwarded to the root element (positioning only — never visual styles). */
  style?: CSSProperties;
}

export function Loader({ size = 'default', label = 'Loading', className, style }: LoaderProps) {
  const variant = getUiCoreConfig().loaderVariant;

  return (
    <span
      role="status"
      aria-label={label}
      aria-live="polite"
      className={['ui-loader', className].filter(Boolean).join(' ')}
      style={style}
    >
      {renderVariant(variant, size)}
    </span>
  );
}

function renderVariant(variant: string, size: NonNullable<LoaderProps['size']>) {
  switch (variant) {
    case 'spinner':
    default:
      return (
        <span aria-hidden="true" className={`ui-loader__spinner ui-loader__spinner--${size}`} />
      );
  }
}

// packages/web-components/src/loader/loader.ts
import { LitElement, html } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { getUiCoreConfig, type LoaderVariant } from '@mszczygiel-projects/ui-core-foundations';
import { loaderStyles } from './loader.styles';
import { motionStyles } from '../styles/motion.styles';
import { resetStyles } from '../styles/reset.styles';

export type { LoaderVariant };

/**
 * Inline spinner indicating a pending asynchronous operation.
 *
 * @element ui-loader
 *
 * @example
 * ```html
 * <ui-loader data-size="small" label="Loading results"></ui-loader>
 * ```
 *
 * @cssprop --loader-color - Spinner color. Defaults to `--color-icon-default`.
 * @cssprop --loader-duration - One full rotation duration. Defaults to `--duration-700`.
 * @cssprop --loader-easing - Rotation easing. Defaults to `--ease-linear`.
 */
@customElement('ui-loader')
export class UiLoader extends LitElement {
  static override styles = [resetStyles, motionStyles, loaderStyles];

  /**
   * Spinner diameter.
   * @default 'default'
   */
  @property({ type: String, reflect: true, attribute: 'data-size' }) size:
    | 'small'
    | 'default'
    | 'large' = 'default';

  /**
   * Accessible name announced by screen readers.
   * @default 'Loading'
   */
  @property({ type: String }) label = 'Loading';

  private get variant(): LoaderVariant {
    return getUiCoreConfig().loaderVariant;
  }

  override render() {
    return html`
      <span role="status" aria-label=${this.label} aria-live="polite">
        ${this.renderVariant()}
      </span>
    `;
  }

  private renderVariant() {
    switch (this.variant) {
      case 'spinner':
      default:
        return html`<span class="spinner" aria-hidden="true"></span>`;
    }
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'ui-loader': UiLoader;
  }
}
