// packages/web-components/src/loader/loader.ts
import { LitElement, html } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { getUiCoreConfig, type LoaderVariant } from '@ui-core/foundations';
import { loaderStyles } from './loader.styles';
import { motionStyles } from '../styles/motion.styles';
import { resetStyles } from '../styles/reset.styles';

export type { LoaderVariant };

@customElement('ui-loader')
export class UiLoader extends LitElement {
  static override styles = [resetStyles, motionStyles, loaderStyles];

  @property({ type: String, reflect: true, attribute: 'data-size' }) size:
    | 'small'
    | 'default'
    | 'large' = 'default';
  @property({ type: String }) label = 'Loading';

  private get variant(): LoaderVariant {
    return getUiCoreConfig().loaderVariant;
  }

  override render() {
    return html`
      <span role="status" aria-label=${this.label} aria-live="polite">
        ${this.renderVariant()}
      </span>
    `;
  }

  private renderVariant() {
    switch (this.variant) {
      case 'spinner':
      default:
        return html`<span class="spinner" aria-hidden="true"></span>`;
    }
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'ui-loader': UiLoader;
  }
}

// packages/react/src/loader/Loader.tsx
import type { CSSProperties } from 'react';
import { getUiCoreConfig } from '@ui-core/foundations';
import './loader.css';

export interface LoaderProps {
  size?: 'small' | 'default' | 'large';
  label?: string;
  className?: string;
  style?: CSSProperties;
}

export function Loader({ size = 'default', label = 'Loading', className, style }: LoaderProps) {
  const variant = getUiCoreConfig().loaderVariant;

  return (
    <span
      role="status"
      aria-label={label}
      aria-live="polite"
      className={['ui-loader', className].filter(Boolean).join(' ')}
      style={style}
    >
      {renderVariant(variant, size)}
    </span>
  );
}

function renderVariant(variant: string, size: NonNullable<LoaderProps['size']>) {
  switch (variant) {
    case 'spinner':
    default:
      return (
        <span aria-hidden="true" className={`ui-loader__spinner ui-loader__spinner--${size}`} />
      );
  }
}
