// packages/react/src/Pagination/Pagination.tsx
import { useId, useState, type AriaAttributes, type CSSProperties, type ReactNode } from 'react';
import { IconChevronLeft, IconChevronRight } from '@mszczygiel-projects/ui-core-icons/react';
import { IconButton } from '../IconButton/IconButton.js';
import { TextField } from '../TextField/TextField.js';
import { pickAriaProps } from '../aria.js';
import { paginate } from './paginate.js';
import './Pagination.css';
import { getUiCoreConfig } from '@mszczygiel-projects/ui-core-foundations';

export type { PaginationEntry } from './paginate.js';

/**
 * Controlled pagination bar: prev/next arrows, numbered page items with
 * ellipsis truncation, an optional consumer-controlled page label, and a
 * jump-to-page field.
 *
 * Controlled-only: the component never changes the page itself — it calls
 * `onChange` (or `onJumpToPage` for jump commits) and waits for a new
 * `currentPage` prop. Below the `48rem` breakpoint the number strip and the
 * jump field collapse and `pageLabel` is centered between the arrows.
 *
 * The jump field is a `TextField` internally; once a NumberField component
 * exists it will swap in without any consumer-facing API change.
 *
 * @example
 * <Pagination
 *   currentPage={page}
 *   totalPages={42}
 *   onChange={setPage}
 *   pageLabel={`Page ${page} of 42`}
 * />
 */
export interface PaginationProps extends AriaAttributes {
  /** Current page, 1-based. */
  currentPage: number;
  /** Total number of pages. */
  totalPages: number;
  /** Called with the target page on prev/next/item clicks (and jump commits unless `onJumpToPage` is set). */
  onChange: (page: number) => void;
  /** Called instead of `onChange` when the jump-to-page field commits a value. */
  onJumpToPage?: (page: number) => void;
  /**
   * Pages shown on each side of the current page.
   * @default 1
   */
  siblingCount?: number;
  /** Optional label content (e.g. "Page 5 of 42"); the only element shown between the arrows on mobile. */
  pageLabel?: ReactNode;
  /**
   * Hides the jump-to-page field.
   * @default false
   */
  hideJumpToPage?: boolean;
  /**
   * Visible caption and accessible name of the jump-to-page field.
   * @default `getUiCoreConfig().labels.pagination.jumpToPage`
   */
  jumpLabel?: string;
  /**
   * Accessible name of the previous-page button.
   * @default `getUiCoreConfig().labels.pagination.previousPage`
   */
  prevLabel?: string;
  /**
   * Accessible name of the next-page button.
   * @default `getUiCoreConfig().labels.pagination.nextPage`
   */
  nextLabel?: string;
  /**
   * Builds the accessible name of a page item.
   * @default page => `Page ${page}`
   */
  getItemAriaLabel?: (page: number) => string;
  /** Extra class names appended to the root element. */
  className?: string;
  /** Inline styles forwarded to the root element (positioning only — never visual styles). */
  style?: CSSProperties;
}

export function Pagination({
  currentPage,
  totalPages,
  onChange,
  onJumpToPage,
  siblingCount = 1,
  pageLabel,
  hideJumpToPage = false,
  jumpLabel,
  prevLabel,
  nextLabel,
  getItemAriaLabel,
  className,
  style,
  'aria-label': ariaLabel,
  ...aria
}: PaginationProps) {
  const total = Math.max(1, Math.floor(totalPages));
  const current = Math.min(Math.max(1, Math.floor(currentPage)), total);
  const entries = paginate(current, total, siblingCount);
  const labels = getUiCoreConfig().labels.pagination;
  const resolvedJumpLabel = jumpLabel ?? labels.jumpToPage;
  const itemAriaLabel = getItemAriaLabel ?? labels.item;
  const jumpLabelId = useId();
  const [draft, setDraft] = useState<string | null>(null);

  const commitJump = () => {
    if (draft === null) return;
    setDraft(null);
    const parsed = Number.parseInt(draft.trim(), 10);
    if (Number.isNaN(parsed)) return;
    const page = Math.min(Math.max(1, parsed), total);
    if (page !== current) (onJumpToPage ?? onChange)(page);
  };

  return (
    <nav
      {...pickAriaProps(aria)}
      aria-label={ariaLabel ?? labels.label}
      className={['ui-pagination', className].filter(Boolean).join(' ')}
      style={style}
    >
      <IconButton
        className="ui-pagination__prev"
        variant="ghost"
        icon={<IconChevronLeft />}
        aria-label={prevLabel ?? labels.previousPage}
        disabled={current <= 1}
        onClick={() => onChange(current - 1)}
      />
      <ul className="ui-pagination__items">
        {entries.map((entry, index) =>
          entry === 'ellipsis' ? (
            <li key={`ellipsis-${index}`} className="ui-pagination__cell" aria-hidden="true">
              <span className="ui-pagination__ellipsis">…</span>
            </li>
          ) : (
            <li key={entry} className="ui-pagination__cell">
              <button
                type="button"
                className={[
                  'ui-pagination__item',
                  entry === current && 'ui-pagination__item--current',
                ]
                  .filter(Boolean)
                  .join(' ')}
                aria-label={itemAriaLabel(entry)}
                aria-current={entry === current ? 'page' : undefined}
                onClick={() => {
                  if (entry !== current) onChange(entry);
                }}
              >
                {entry}
              </button>
            </li>
          ),
        )}
      </ul>
      <IconButton
        className="ui-pagination__next"
        variant="ghost"
        icon={<IconChevronRight />}
        aria-label={nextLabel ?? labels.nextPage}
        disabled={current >= total}
        onClick={() => onChange(current + 1)}
      />
      {(pageLabel != null || !hideJumpToPage) && (
        <div className="ui-pagination__meta">
          {pageLabel != null && <span className="ui-pagination__label">{pageLabel}</span>}
          {!hideJumpToPage && (
            <div className="ui-pagination__jump">
              <span id={jumpLabelId} className="ui-pagination__jump-label">
                {resolvedJumpLabel}
              </span>
              <TextField
                className="ui-pagination__jump-field"
                value={draft ?? String(current)}
                onChange={setDraft}
                inputMode="numeric"
                autoComplete="off"
                aria-labelledby={jumpLabelId}
                onKeyDown={(event) => {
                  if (event.key === 'Enter') commitJump();
                }}
                onBlur={commitJump}
              />
            </div>
          )}
        </div>
      )}
    </nav>
  );
}

// packages/web-components/src/pagination/pagination.ts
import { LitElement, html, nothing } from 'lit';
import { customElement, property, state } from 'lit/decorators.js';
import { unsafeSVG } from 'lit/directives/unsafe-svg.js';
import { svgMap } from '@mszczygiel-projects/ui-core-icons';
import { paginationStyles } from './pagination.styles.js';
import { focusStyles } from '../styles/focus.styles.js';
import { resetStyles } from '../styles/reset.styles.js';
import { paginate } from './paginate.js';
import '../icon-button/icon-button.js';
import { getUiCoreConfig } from '@mszczygiel-projects/ui-core-foundations';

export type { PaginationEntry } from './paginate.js';

export interface PaginationChangeDetail {
  /** Target page, already clamped to `[1, totalPages]`. */
  page: number;
  /** Which control requested the change. */
  source: 'prev' | 'next' | 'item' | 'jump';
}

/**
 * Controlled pagination bar: prev/next arrows, numbered page items with
 * ellipsis truncation, an optional consumer-controlled page label, and a
 * jump-to-page field. Controlled-only: the component never changes the page
 * itself — it fires `ui-change` and waits for a new `current-page` value.
 * Below the `48rem` breakpoint the number strip and the jump field collapse
 * and the `page-label` slot is centered between the arrows.
 *
 * The jump field mirrors TextField's outline styling via control tokens; once
 * a NumberField component exists it will swap in without any consumer-facing
 * API change.
 *
 * @element ui-pagination
 *
 * @example
 * ```html
 * <ui-pagination current-page="5" total-pages="42">
 *   <span slot="page-label">Page 5 of 42</span>
 * </ui-pagination>
 * ```
 *
 * @slot page-label - Optional label content; the only element shown between the arrows on mobile.
 *
 * @fires {CustomEvent} ui-change - A page was requested; `detail.page` carries the target page, `detail.source` one of `prev | next | item | jump`.
 */
@customElement('ui-pagination')
export class UiPagination extends LitElement {
  static override styles = [resetStyles, focusStyles, paginationStyles];

  /**
   * Current page, 1-based.
   * @default 1
   */
  @property({ type: Number, reflect: true, attribute: 'current-page' }) currentPage = 1;

  /**
   * Total number of pages.
   * @default 1
   */
  @property({ type: Number, reflect: true, attribute: 'total-pages' }) totalPages = 1;

  /**
   * Pages shown on each side of the current page.
   * @default 1
   */
  @property({ type: Number, reflect: true, attribute: 'sibling-count' }) siblingCount = 1;

  /**
   * Hides the jump-to-page field.
   * @default false
   */
  @property({ type: Boolean, reflect: true, attribute: 'hide-jump-to-page' })
  hideJumpToPage = false;

  /**
   * Visible caption and accessible name of the jump-to-page field.
   * @default `getUiCoreConfig().labels.pagination.jumpToPage`
   */
  @property({ type: String, attribute: 'jump-label' }) jumpLabel?: string;

  /**
   * Accessible name of the previous-page button.
   * @default `getUiCoreConfig().labels.pagination.previousPage`
   */
  @property({ type: String, attribute: 'prev-label' }) prevLabel?: string;

  /**
   * Accessible name of the next-page button.
   * @default `getUiCoreConfig().labels.pagination.nextPage`
   */
  @property({ type: String, attribute: 'next-label' }) nextLabel?: string;

  /**
   * Accessible name of the root `<nav>`.
   * @default `getUiCoreConfig().labels.pagination.label`
   */
  @property({ type: String }) label?: string;

  /**
   * Builds the accessible name of a page item. Property-only (function type).
   * @default page => `Page ${page}`
   */
  @property({ attribute: false }) itemAriaLabel?: (page: number) => string;

  /** Draft value of the jump field; `null` mirrors `currentPage`. */
  @state() private _draft: string | null = null;

  @state() private _hasPageLabel = false;

  private get _total(): number {
    return Math.max(1, Math.floor(this.totalPages));
  }

  private get _current(): number {
    return Math.min(Math.max(1, Math.floor(this.currentPage)), this._total);
  }

  private _emitChange(page: number, source: PaginationChangeDetail['source']) {
    this.dispatchEvent(
      new CustomEvent<PaginationChangeDetail>('ui-change', {
        detail: { page, source },
        bubbles: true,
        composed: true,
      }),
    );
  }

  private _onItemClick(page: number) {
    if (page !== this._current) this._emitChange(page, 'item');
  }

  private _onPrevClick() {
    if (this._current > 1) this._emitChange(this._current - 1, 'prev');
  }

  private _onNextClick() {
    if (this._current < this._total) this._emitChange(this._current + 1, 'next');
  }

  private _onJumpInput(event: Event) {
    this._draft = (event.target as HTMLInputElement).value;
  }

  private _onJumpKeydown(event: KeyboardEvent) {
    if (event.key === 'Enter') this._commitJump();
  }

  private _commitJump() {
    if (this._draft === null) return;
    const parsed = Number.parseInt(this._draft.trim(), 10);
    this._draft = null;
    if (!Number.isNaN(parsed)) {
      const page = Math.min(Math.max(1, parsed), this._total);
      if (page !== this._current) this._emitChange(page, 'jump');
    }
    // Rapid input + commit can coalesce into one update, so the draft never
    // reaches the template binding and Lit's dirty-check would skip resetting
    // the input — sync the DOM value imperatively (after the change event, so
    // a synchronous currentPage update is already reflected).
    const input = this.shadowRoot?.querySelector<HTMLInputElement>('.jump-input');
    if (input) input.value = String(this._current);
  }

  private _onPageLabelSlotChange(event: Event) {
    const slot = event.target as HTMLSlotElement;
    this._hasPageLabel = slot
      .assignedNodes({ flatten: true })
      .some(
        (node) => node.nodeType === Node.ELEMENT_NODE || (node.textContent ?? '').trim() !== '',
      );
  }

  override render() {
    const current = this._current;
    const total = this._total;
    const entries = paginate(current, total, this.siblingCount);
    const labels = getUiCoreConfig().labels.pagination;
    const jumpLabel = this.jumpLabel ?? labels.jumpToPage;
    const itemAriaLabel = this.itemAriaLabel ?? labels.item;

    return html`
      <nav class="root" aria-label=${this.label ?? labels.label}>
        <ui-icon-button
          class="prev"
          variant="ghost"
          label=${this.prevLabel ?? labels.previousPage}
          ?disabled=${current <= 1}
          @click=${this._onPrevClick}
        >
          ${unsafeSVG(svgMap['icon-chevron-left'])}
        </ui-icon-button>
        <ul class="items">
          ${entries.map((entry) =>
            entry === 'ellipsis'
              ? html` <li class="cell" aria-hidden="true"><span class="ellipsis">…</span></li> `
              : html`
                  <li class="cell">
                    <button
                      type="button"
                      class="item ${entry === current ? 'item--current' : ''}"
                      aria-label=${itemAriaLabel(entry)}
                      aria-current=${entry === current ? 'page' : nothing}
                      @click=${() => this._onItemClick(entry)}
                    >
                      ${entry}
                    </button>
                  </li>
                `,
          )}
        </ul>
        <ui-icon-button
          class="next"
          variant="ghost"
          label=${this.nextLabel ?? labels.nextPage}
          ?disabled=${current >= total}
          @click=${this._onNextClick}
        >
          ${unsafeSVG(svgMap['icon-chevron-right'])}
        </ui-icon-button>
        <div class="meta">
          <span class="page-label ${this._hasPageLabel ? '' : 'empty'}">
            <slot name="page-label" @slotchange=${this._onPageLabelSlotChange}></slot>
          </span>
          ${this.hideJumpToPage
            ? nothing
            : html`
                <div class="jump">
                  <span class="jump-label" aria-hidden="true">${jumpLabel}</span>
                  <input
                    class="jump-input"
                    type="text"
                    inputmode="numeric"
                    autocomplete="off"
                    aria-label=${jumpLabel}
                    .value=${this._draft ?? String(current)}
                    @input=${this._onJumpInput}
                    @keydown=${this._onJumpKeydown}
                    @blur=${this._commitJump}
                  />
                </div>
              `}
        </div>
      </nav>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'ui-pagination': UiPagination;
  }
}
