// packages/web-components/src/file-input-field/file-input-field.ts
import { LitElement, html, nothing, type PropertyValues } from 'lit';
import { customElement, property, query, state } from 'lit/decorators.js';
import { unsafeSVG } from 'lit/directives/unsafe-svg.js';
import { svgMap } from '@mszczygiel-projects/ui-core-icons';
import { getUiCoreConfig } from '@mszczygiel-projects/ui-core-foundations';
import { fileInputFieldStyles } from './file-input-field.styles.js';
import { controlFieldStyles } from '../styles/control-field.styles.js';
import { motionStyles } from '../styles/motion.styles.js';
import { resetStyles } from '../styles/reset.styles.js';

export type FileInputFieldVariant = 'outline' | 'filled';
export type FileInputFieldSize = 'small' | 'default' | 'large';
export type FileInputFieldState = 'default' | 'success' | 'error' | 'disabled';

/** Why a dropped or picked file did not make it into `files`. */
export type FileInputFieldRejectReason = 'type' | 'size' | 'count';

export interface FileInputFieldRejection {
  file: File;
  reason: FileInputFieldRejectReason;
}

/** Which presentation the field is currently in — mirrors the `Value` axis in Figma. */
export type FileInputFieldMode = 'empty' | 'filled' | 'list';

const KILO = 1024;

/** Non-localized fallback. Consumers wanting localized output pass `formatSize`. */
function defaultFormatSize(bytes: number): string {
  if (bytes < KILO) return `${bytes} B`;
  const units = ['KB', 'MB', 'GB', 'TB'];
  let value = bytes / KILO;
  let unit = 0;
  while (value >= KILO && unit < units.length - 1) {
    value /= KILO;
    unit += 1;
  }
  return `${value < 10 ? value.toFixed(1) : Math.round(value)} ${units[unit]}`;
}

/** Matches one `accept` entry: `.png`, `image/*` or `image/png`. */
function matchesAcceptEntry(file: File, entry: string): boolean {
  const rule = entry.trim().toLowerCase();
  if (!rule) return true;
  if (rule.startsWith('.')) return file.name.toLowerCase().endsWith(rule);
  if (rule.endsWith('/*')) return file.type.toLowerCase().startsWith(rule.slice(0, -1));
  return file.type.toLowerCase() === rule;
}

/**
 * Form-associated file input with a drag-and-drop zone, validation states, and
 * either an in-place preview or a list of the selected files.
 *
 * The presentation is derived, never set by hand: no files renders the prompt,
 * a single image in single-file mode renders a preview with Replace/Remove,
 * and anything else keeps the drop zone and stacks the files below it.
 *
 * @element ui-file-input-field
 *
 * @example
 * ```html
 * <ui-file-input-field
 *   label="Photo"
 *   description="PNG, SVG — max 2 MB"
 *   accept="image/png,image/svg+xml"
 *   max-size="2097152"
 * ></ui-file-input-field>
 * ```
 *
 * @slot actions - Extra controls appended next to Replace and Remove in the preview.
 *
 * @fires {CustomEvent} ui-change - `detail.files` carries the accepted files after any change.
 * @fires {CustomEvent} ui-reject - `detail.rejections` lists files refused by `accept`, `maxSize` or `maxFiles`.
 * @fires {CustomEvent} ui-remove - `detail.file` and `detail.index` identify the removed file.
 *
 * @cssprop --file-input-radius - Drop zone corner radius. Defaults to `--control-radius`.
 * @cssprop --file-input-preview-max-height - Cap on the in-place preview height.
 */
@customElement('ui-file-input-field')
export class UiFileInputField extends LitElement {
  static readonly formAssociated = true;
  static override styles = [resetStyles, motionStyles, controlFieldStyles, fileInputFieldStyles];

  /**
   * Drop zone style: dashed outline over the page background, or a filled block.
   * @default 'outline'
   */
  @property({ type: String, reflect: true }) variant: FileInputFieldVariant = 'outline';

  /**
   * Drop zone height and typography scale.
   * @default 'default'
   */
  @property({ type: String, reflect: true, attribute: 'data-size' })
  size: FileInputFieldSize = 'default';

  /** Label text rendered above the drop zone. */
  @property({ type: String, reflect: true }) label?: string;

  /**
   * Prompt inside the empty drop zone. Falls back to the configured
   * `labels.fileInput.browse`.
   */
  @property({ type: String, reflect: true }) prompt?: string;

  /** Secondary line under the prompt — accepted formats, size limits, etc. */
  @property({ type: String, reflect: true }) description?: string;

  /** Helper text rendered below the field, linked via `aria-describedby`. */
  @property({ type: String, reflect: true }) hint?: string;

  /**
   * Validation state; `error` also sets `aria-invalid`, `disabled` also disables
   * the input.
   * @default 'default'
   */
  @property({ type: String, reflect: true }) state: FileInputFieldState = 'default';

  /** Native `accept` filter, also enforced on dropped files. */
  @property({ type: String, reflect: true }) accept?: string;

  /** Allows selecting more than one file. */
  @property({ type: Boolean, reflect: true }) multiple = false;

  /** Largest accepted file size in bytes. */
  @property({ type: Number, attribute: 'max-size' }) maxSize?: number;

  /** Largest accepted number of files. */
  @property({ type: Number, attribute: 'max-files' }) maxFiles?: number;

  /** Currently selected files. Property only — a `File` cannot cross an attribute. */
  @property({ attribute: false }) files: File[] = [];

  /** Form field name used on submission. */
  @property({ type: String }) name?: string;

  /** Disables the whole field. */
  @property({ type: Boolean, reflect: true }) disabled = false;

  /** Marks the field as required for form submission. */
  @property({ type: Boolean, reflect: true }) required = false;

  /** Label of the Replace button. */
  @property({ type: String, attribute: 'replace-label' }) replaceLabel?: string;

  /** Accessible name of a file's remove button. */
  @property({ attribute: false }) removeLabel?: (fileName: string) => string;

  /** Formats the byte count shown next to a file name. */
  @property({ attribute: false }) formatSize?: (bytes: number) => string;

  @state() private _formDisabled = false;

  @query('.input') private _inputEl!: HTMLInputElement | null;

  private _internals: ElementInternals;
  private _previewUrls = new Map<File, string>();
  /** Nested dragenter/dragleave pairs fire per child; counting keeps the state stable. */
  private _dragDepth = 0;

  constructor() {
    super();
    this._internals = this.attachInternals();
  }

  override connectedCallback() {
    super.connectedCallback();
    this._syncFormValue();
  }

  override disconnectedCallback() {
    super.disconnectedCallback();
    this._revokeAllPreviews();
  }

  private get _isDisabled(): boolean {
    return this.disabled || this.state === 'disabled' || this._formDisabled;
  }

  /** Which presentation to render — the code twin of Figma's `Value` axis. */
  get mode(): FileInputFieldMode {
    if (this.files.length === 0) return 'empty';
    if (!this.multiple && this.files.length === 1 && this.files[0].type.startsWith('image/')) {
      return 'filled';
    }
    return 'list';
  }

  protected override updated(changed: PropertyValues<this>): void {
    if (changed.has('files') || changed.has('disabled') || changed.has('state')) {
      this._syncFormValue();
    }
    if (changed.has('files')) this._revokeStalePreviews();
    this.setAttribute('data-value', this.mode);
  }

  formDisabledCallback(disabled: boolean) {
    this._formDisabled = disabled;
    this._syncFormValue();
  }

  formResetCallback() {
    this._setFiles([]);
  }

  private _syncFormValue() {
    if (this._isDisabled || this.files.length === 0) {
      this._internals.setFormValue(null);
      return;
    }
    const data = new FormData();
    for (const file of this.files) data.append(this.name ?? 'files', file);
    this._internals.setFormValue(data);
  }

  private _previewUrl(file: File): string {
    let url = this._previewUrls.get(file);
    if (!url) {
      url = URL.createObjectURL(file);
      this._previewUrls.set(file, url);
    }
    return url;
  }

  private _revokeStalePreviews() {
    const live = new Set(this.files);
    for (const [file, url] of this._previewUrls) {
      if (live.has(file)) continue;
      URL.revokeObjectURL(url);
      this._previewUrls.delete(file);
    }
  }

  private _revokeAllPreviews() {
    for (const url of this._previewUrls.values()) URL.revokeObjectURL(url);
    this._previewUrls.clear();
  }

  private _validate(incoming: File[]): {
    accepted: File[];
    rejections: FileInputFieldRejection[];
  } {
    const accepted: File[] = [];
    const rejections: FileInputFieldRejection[] = [];
    const rules = this.accept?.split(',').filter((entry) => entry.trim()) ?? [];
    const kept = this.multiple ? [...this.files] : [];

    for (const file of incoming) {
      if (rules.length && !rules.some((rule) => matchesAcceptEntry(file, rule))) {
        rejections.push({ file, reason: 'type' });
        continue;
      }
      if (this.maxSize !== undefined && file.size > this.maxSize) {
        rejections.push({ file, reason: 'size' });
        continue;
      }
      if (this.maxFiles !== undefined && kept.length + accepted.length >= this.maxFiles) {
        rejections.push({ file, reason: 'count' });
        continue;
      }
      accepted.push(file);
      if (!this.multiple) break;
    }
    return { accepted, rejections };
  }

  private _setFiles(files: File[]) {
    this.files = files;
    this._syncFormValue();
    this.dispatchEvent(
      new CustomEvent('ui-change', {
        detail: { files: this.files },
        bubbles: true,
        composed: true,
      }),
    );
  }

  private _ingest(incoming: File[]) {
    if (this._isDisabled || incoming.length === 0) return;
    const { accepted, rejections } = this._validate(incoming);
    if (rejections.length) {
      this.dispatchEvent(
        new CustomEvent('ui-reject', { detail: { rejections }, bubbles: true, composed: true }),
      );
    }
    if (!accepted.length) return;
    this._setFiles(this.multiple ? [...this.files, ...accepted] : accepted);
  }

  private _openPicker() {
    if (this._isDisabled) return;
    this._inputEl?.click();
  }

  private _onInputChange(event: Event) {
    const input = event.target as HTMLInputElement;
    this._ingest(Array.from(input.files ?? []));
    // Lets the same file be picked again right after it was removed.
    input.value = '';
  }

  private _onDragOver(event: DragEvent) {
    if (this._isDisabled) return;
    event.preventDefault();
    if (event.dataTransfer) event.dataTransfer.dropEffect = 'copy';
  }

  private _onDragEnter(event: DragEvent) {
    if (this._isDisabled) return;
    event.preventDefault();
    this._dragDepth += 1;
    this.toggleAttribute('data-dragover', true);
  }

  private _onDragLeave() {
    if (this._isDisabled) return;
    this._dragDepth = Math.max(0, this._dragDepth - 1);
    if (this._dragDepth === 0) this.toggleAttribute('data-dragover', false);
  }

  private _onDrop(event: DragEvent) {
    if (this._isDisabled) return;
    event.preventDefault();
    this._dragDepth = 0;
    this.toggleAttribute('data-dragover', false);
    this._ingest(Array.from(event.dataTransfer?.files ?? []));
  }

  private _onRemove(file: File, index: number, event: Event) {
    event.stopPropagation();
    if (this._isDisabled) return;
    const next = this.files.filter((_, i) => i !== index);
    this.dispatchEvent(
      new CustomEvent('ui-remove', { detail: { file, index }, bubbles: true, composed: true }),
    );
    this._setFiles(next);
  }

  private _onReplace(event: Event) {
    event.stopPropagation();
    this._openPicker();
  }

  private _describedBy(): string | typeof nothing {
    // The description only exists in the prompt, which the preview replaces —
    // pointing aria-describedby at an id that is not in the tree says nothing.
    const ids = [
      this.description && this.mode !== 'filled' ? 'description' : '',
      this.hint ? 'hint' : '',
    ].filter(Boolean);
    return ids.length ? ids.join(' ') : nothing;
  }

  private _meta(file: File): string {
    const format = this.formatSize ?? defaultFormatSize;
    const dot = file.name.lastIndexOf('.');
    const extension = dot > 0 ? file.name.slice(dot + 1).toUpperCase() : '';
    const size = format(file.size);
    return extension ? `${extension} · ${size}` : size;
  }

  private _renderPrompt() {
    const labels = getUiCoreConfig().labels.fileInput;
    return html`
      <span class="icon">${unsafeSVG(svgMap['icon-upload'])}</span>
      <p class="prompt">${this.prompt ?? labels.browse}</p>
      ${this.description
        ? html`<p id="description" class="description">${this.description}</p>`
        : nothing}
    `;
  }

  private _renderPreview() {
    const labels = getUiCoreConfig().labels.fileInput;
    const file = this.files[0];
    const removeLabel = (this.removeLabel ?? labels.remove)(file.name);
    return html`
      <span class="preview">
        <img src=${this._previewUrl(file)} alt=${file.name} />
      </span>
      <span class="actions">
        <button
          type="button"
          class="action"
          ?disabled=${this._isDisabled}
          @click=${this._onReplace}
        >
          ${this.replaceLabel ?? labels.replace}
        </button>
        <button
          type="button"
          class="action action--icon"
          aria-label=${removeLabel}
          ?disabled=${this._isDisabled}
          @click=${(e: Event) => this._onRemove(file, 0, e)}
        >
          ${unsafeSVG(svgMap['icon-delete'])}
        </button>
        <slot name="actions"></slot>
      </span>
    `;
  }

  private _renderList() {
    const labels = getUiCoreConfig().labels.fileInput;
    const resolveRemove = this.removeLabel ?? labels.remove;
    return html`
      <ul class="list">
        ${this.files.map(
          (file, index) => html`
            <li class="item">
              <span class="thumb">
                ${file.type.startsWith('image/')
                  ? html`<img src=${this._previewUrl(file)} alt="" />`
                  : unsafeSVG(svgMap['icon-file'])}
              </span>
              <span class="info">
                <span class="name">${file.name}</span>
                <span class="meta">${this._meta(file)}</span>
              </span>
              <button
                type="button"
                class="action action--icon"
                aria-label=${resolveRemove(file.name)}
                ?disabled=${this._isDisabled}
                @click=${(e: Event) => this._onRemove(file, index, e)}
              >
                ${unsafeSVG(svgMap['icon-delete'])}
              </button>
            </li>
          `,
        )}
      </ul>
    `;
  }

  override render() {
    const mode = this.mode;
    return html`
      ${this.label ? html`<label class="label" for="input">${this.label}</label>` : nothing}
      <input
        id="input"
        class="input"
        type="file"
        accept=${this.accept ?? nothing}
        name=${this.name ?? nothing}
        ?multiple=${this.multiple}
        ?disabled=${this._isDisabled}
        ?required=${this.required}
        aria-invalid=${this.state === 'error' ? 'true' : nothing}
        aria-describedby=${this._describedBy()}
        @change=${this._onInputChange}
      />
      <div
        class="dropzone"
        @click=${this._openPicker}
        @dragenter=${this._onDragEnter}
        @dragover=${this._onDragOver}
        @dragleave=${this._onDragLeave}
        @drop=${this._onDrop}
      >
        ${mode === 'filled' ? this._renderPreview() : this._renderPrompt()}
      </div>
      ${mode === 'list' ? this._renderList() : nothing}
      ${this.hint ? html`<p id="hint" class="hint">${this.hint}</p>` : nothing}
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'ui-file-input-field': UiFileInputField;
  }
}

// packages/react/src/FileInputField/FileInputField.tsx
import {
  forwardRef,
  useCallback,
  useEffect,
  useId,
  useMemo,
  useRef,
  useState,
  type CSSProperties,
  type DragEvent,
  type ReactNode,
} from 'react';
import { IconDelete, IconFile, IconUpload } from '@mszczygiel-projects/ui-core-icons/react';
import { getUiCoreConfig } from '@mszczygiel-projects/ui-core-foundations';
import './FileInputField.css';

export type FileInputFieldVariant = 'outline' | 'filled';
export type FileInputFieldSize = 'small' | 'default' | 'large';
export type FileInputFieldState = 'default' | 'success' | 'error' | 'disabled';

/** Why a dropped or picked file did not make it into the selection. */
export type FileInputFieldRejectReason = 'type' | 'size' | 'count';

export interface FileInputFieldRejection {
  file: File;
  reason: FileInputFieldRejectReason;
}

/** Which presentation the field is currently in — mirrors the `Value` axis in Figma. */
export type FileInputFieldMode = 'empty' | 'filled' | 'list';

const KILO = 1024;

/** Non-localized fallback. Consumers wanting localized output pass `formatSize`. */
function defaultFormatSize(bytes: number): string {
  if (bytes < KILO) return `${bytes} B`;
  const units = ['KB', 'MB', 'GB', 'TB'];
  let value = bytes / KILO;
  let unit = 0;
  while (value >= KILO && unit < units.length - 1) {
    value /= KILO;
    unit += 1;
  }
  return `${value < 10 ? value.toFixed(1) : Math.round(value)} ${units[unit]}`;
}

/** Matches one `accept` entry: `.png`, `image/*` or `image/png`. */
function matchesAcceptEntry(file: File, entry: string): boolean {
  const rule = entry.trim().toLowerCase();
  if (!rule) return true;
  if (rule.startsWith('.')) return file.name.toLowerCase().endsWith(rule);
  if (rule.endsWith('/*')) return file.type.toLowerCase().startsWith(rule.slice(0, -1));
  return file.type.toLowerCase() === rule;
}

function isImage(file: File): boolean {
  return file.type.startsWith('image/');
}

/**
 * File input with a drag-and-drop zone, validation states, and either an
 * in-place preview or a list of the selected files.
 *
 * The presentation is derived, never set by hand: no files renders the prompt,
 * a single image in single-file mode renders a preview with Replace/Remove,
 * and anything else keeps the drop zone and stacks the files below it.
 *
 * @example
 * <FileInputField
 *   label="Photo"
 *   description="PNG, SVG — max 2 MB"
 *   accept="image/png,image/svg+xml"
 *   maxSize={2 * 1024 * 1024}
 *   onChange={setFiles}
 * />
 */
export interface FileInputFieldProps {
  /**
   * Drop zone style: dashed outline over the page background, or a filled block.
   * @default 'outline'
   */
  variant?: FileInputFieldVariant;
  /**
   * Drop zone height and typography scale.
   * @default 'default'
   */
  size?: FileInputFieldSize;
  /** Label text rendered above the drop zone. */
  label?: string;
  /** Prompt inside the empty drop zone. Falls back to `labels.fileInput.browse`. */
  prompt?: string;
  /** Secondary line under the prompt — accepted formats, size limits, etc. */
  description?: string;
  /** Helper text rendered below the field, linked via `aria-describedby`. */
  hint?: string;
  /**
   * Validation state; `error` sets `aria-invalid`, `disabled` disables the input.
   * @default 'default'
   */
  state?: FileInputFieldState;
  /** Native `accept` filter, also enforced on dropped files. */
  accept?: string;
  /** Allows selecting more than one file. */
  multiple?: boolean;
  /** Largest accepted file size in bytes. */
  maxSize?: number;
  /** Largest accepted number of files. */
  maxFiles?: number;
  /** Selected files. Passing it makes the component controlled. */
  files?: File[];
  /** Initial selection for the uncontrolled component. */
  defaultFiles?: File[];
  /** Called with the full selection whenever it changes. */
  onChange?: (files: File[]) => void;
  /** Called with the files refused by `accept`, `maxSize` or `maxFiles`. */
  onReject?: (rejections: FileInputFieldRejection[]) => void;
  /** Called just before a file leaves the selection. */
  onRemove?: (file: File, index: number) => void;
  /** Form field name used on submission. */
  name?: string;
  /** Marks the field as required for form submission. */
  required?: boolean;
  /** Label of the Replace button. */
  replaceLabel?: string;
  /** Accessible name of a file's remove button. */
  removeLabel?: (fileName: string) => string;
  /** Formats the byte count shown next to a file name. */
  formatSize?: (bytes: number) => string;
  /** Extra controls appended next to Replace and Remove in the preview. */
  actions?: ReactNode;
  /** Extra class names appended to the root element. */
  className?: string;
  /** Inline styles forwarded to the root element (positioning only — never visual styles). */
  style?: CSSProperties;
}

export const FileInputField = forwardRef<HTMLInputElement, FileInputFieldProps>(
  function FileInputField(
    {
      variant = 'outline',
      size = 'default',
      label,
      prompt,
      description,
      hint,
      state = 'default',
      accept,
      multiple = false,
      maxSize,
      maxFiles,
      files,
      defaultFiles,
      onChange,
      onReject,
      onRemove,
      name,
      required,
      replaceLabel,
      removeLabel,
      formatSize,
      actions,
      className,
      style,
    }: FileInputFieldProps,
    ref,
  ) {
    const generatedId = useId();
    const inputId = `${generatedId}-input`;
    const descriptionId = `${generatedId}-description`;
    const hintId = `${generatedId}-hint`;

    const inputRef = useRef<HTMLInputElement | null>(null);
    const [internalFiles, setInternalFiles] = useState<File[]>(defaultFiles ?? []);
    const [isDragover, setIsDragover] = useState(false);
    // Nested dragenter/dragleave pairs fire per child; counting keeps it stable.
    const dragDepth = useRef(0);

    const isControlled = files !== undefined;
    const selected = isControlled ? files : internalFiles;
    const isDisabled = state === 'disabled';

    const labels = getUiCoreConfig().labels.fileInput;
    const resolveRemoveLabel = removeLabel ?? labels.remove;
    const resolveSize = formatSize ?? defaultFormatSize;

    const mode: FileInputFieldMode =
      selected.length === 0
        ? 'empty'
        : !multiple && selected.length === 1 && isImage(selected[0])
          ? 'filled'
          : 'list';

    /*
     * Object URLs are owned by this component: created for the files currently
     * in the selection, revoked as soon as a file leaves it or the component
     * unmounts. Deriving them in render without this bookkeeping leaks.
     */
    const previewUrls = useMemo(() => {
      const map = new Map<File, string>();
      for (const file of selected) {
        if (isImage(file)) map.set(file, URL.createObjectURL(file));
      }
      return map;
    }, [selected]);

    useEffect(() => {
      return () => {
        for (const url of previewUrls.values()) URL.revokeObjectURL(url);
      };
    }, [previewUrls]);

    const commit = useCallback(
      (next: File[]) => {
        if (!isControlled) setInternalFiles(next);
        onChange?.(next);
      },
      [isControlled, onChange],
    );

    const ingest = useCallback(
      (incoming: File[]) => {
        if (isDisabled || incoming.length === 0) return;
        const rules = accept?.split(',').filter((entry) => entry.trim()) ?? [];
        const kept = multiple ? [...selected] : [];
        const accepted: File[] = [];
        const rejections: FileInputFieldRejection[] = [];

        for (const file of incoming) {
          if (rules.length && !rules.some((rule) => matchesAcceptEntry(file, rule))) {
            rejections.push({ file, reason: 'type' });
            continue;
          }
          if (maxSize !== undefined && file.size > maxSize) {
            rejections.push({ file, reason: 'size' });
            continue;
          }
          if (maxFiles !== undefined && kept.length + accepted.length >= maxFiles) {
            rejections.push({ file, reason: 'count' });
            continue;
          }
          accepted.push(file);
          if (!multiple) break;
        }

        if (rejections.length) onReject?.(rejections);
        if (!accepted.length) return;
        commit(multiple ? [...selected, ...accepted] : accepted);
      },
      [accept, commit, isDisabled, maxFiles, maxSize, multiple, onReject, selected],
    );

    const openPicker = () => {
      if (isDisabled) return;
      inputRef.current?.click();
    };

    const handleRemove = (file: File, index: number) => {
      if (isDisabled) return;
      onRemove?.(file, index);
      commit(selected.filter((_, i) => i !== index));
    };

    const handleDragEnter = (event: DragEvent<HTMLDivElement>) => {
      if (isDisabled) return;
      event.preventDefault();
      dragDepth.current += 1;
      setIsDragover(true);
    };

    const handleDragLeave = () => {
      if (isDisabled) return;
      dragDepth.current = Math.max(0, dragDepth.current - 1);
      if (dragDepth.current === 0) setIsDragover(false);
    };

    const handleDrop = (event: DragEvent<HTMLDivElement>) => {
      if (isDisabled) return;
      event.preventDefault();
      dragDepth.current = 0;
      setIsDragover(false);
      ingest(Array.from(event.dataTransfer?.files ?? []));
    };

    const meta = (file: File) => {
      const dot = file.name.lastIndexOf('.');
      const extension = dot > 0 ? file.name.slice(dot + 1).toUpperCase() : '';
      const formatted = resolveSize(file.size);
      return extension ? `${extension} · ${formatted}` : formatted;
    };

    const rootClass = [
      'ui-file-input-field',
      `ui-file-input-field--${variant}`,
      size !== 'default' && `ui-file-input-field--${size}`,
      state !== 'default' && `ui-file-input-field--state-${state}`,
      isDragover && 'ui-file-input-field--dragover',
      'ui-control-field',
      `ui-control-field--${variant}`,
      size !== 'default' && `ui-control-field--${size}`,
      className,
    ]
      .filter(Boolean)
      .join(' ');

    // The description only exists in the prompt, which the preview replaces —
    // pointing aria-describedby at an id that is not in the tree says nothing.
    const describedBy =
      [description && mode !== 'filled' ? descriptionId : '', hint ? hintId : '']
        .filter(Boolean)
        .join(' ') || undefined;

    return (
      <div className={rootClass} style={style} data-value={mode}>
        {label && (
          <label className="ui-file-input-field__label" htmlFor={inputId}>
            {label}
          </label>
        )}
        <input
          id={inputId}
          className="ui-file-input-field__input"
          type="file"
          ref={(node) => {
            inputRef.current = node;
            if (typeof ref === 'function') ref(node);
            else if (ref) ref.current = node;
          }}
          accept={accept}
          name={name}
          multiple={multiple}
          disabled={isDisabled}
          required={required}
          aria-invalid={state === 'error' ? 'true' : undefined}
          aria-describedby={describedBy}
          onChange={(event) => {
            ingest(Array.from(event.target.files ?? []));
            // Lets the same file be picked again right after it was removed.
            event.target.value = '';
          }}
        />
        <div
          className="ui-file-input-field__dropzone"
          onClick={openPicker}
          onDragEnter={handleDragEnter}
          onDragOver={(event) => {
            if (isDisabled) return;
            event.preventDefault();
            event.dataTransfer.dropEffect = 'copy';
          }}
          onDragLeave={handleDragLeave}
          onDrop={handleDrop}
        >
          {mode === 'filled' ? (
            <>
              <span className="ui-file-input-field__preview">
                <img src={previewUrls.get(selected[0])} alt={selected[0].name} />
              </span>
              <span className="ui-file-input-field__actions">
                <button
                  type="button"
                  className="ui-file-input-field__action"
                  disabled={isDisabled}
                  onClick={(event) => {
                    event.stopPropagation();
                    openPicker();
                  }}
                >
                  {replaceLabel ?? labels.replace}
                </button>
                <button
                  type="button"
                  className="ui-file-input-field__action ui-file-input-field__action--icon"
                  aria-label={resolveRemoveLabel(selected[0].name)}
                  disabled={isDisabled}
                  onClick={(event) => {
                    event.stopPropagation();
                    handleRemove(selected[0], 0);
                  }}
                >
                  <IconDelete />
                </button>
                {actions}
              </span>
            </>
          ) : (
            <>
              <span className="ui-file-input-field__icon">
                <IconUpload />
              </span>
              <p className="ui-file-input-field__prompt">{prompt ?? labels.browse}</p>
              {description && (
                <p id={descriptionId} className="ui-file-input-field__description">
                  {description}
                </p>
              )}
            </>
          )}
        </div>
        {mode === 'list' && (
          <ul className="ui-file-input-field__list">
            {selected.map((file, index) => (
              <li className="ui-file-input-field__item" key={`${file.name}-${index}`}>
                <span className="ui-file-input-field__thumb">
                  {isImage(file) ? <img src={previewUrls.get(file)} alt="" /> : <IconFile />}
                </span>
                <span className="ui-file-input-field__info">
                  <span className="ui-file-input-field__name">{file.name}</span>
                  <span className="ui-file-input-field__meta">{meta(file)}</span>
                </span>
                <button
                  type="button"
                  className="ui-file-input-field__action ui-file-input-field__action--icon"
                  aria-label={resolveRemoveLabel(file.name)}
                  disabled={isDisabled}
                  onClick={() => handleRemove(file, index)}
                >
                  <IconDelete />
                </button>
              </li>
            ))}
          </ul>
        )}
        {hint && (
          <p id={hintId} className="ui-file-input-field__hint">
            {hint}
          </p>
        )}
      </div>
    );
  },
);
