// packages/react/src/CheckboxField/CheckboxField.tsx
import { useId, useEffect, useRef, type CSSProperties } from 'react';
import './CheckboxField.css';

export type CheckboxFieldState = 'default' | 'error' | 'disabled';

/**
 * Checkbox with label and hint, supporting controlled, uncontrolled, and indeterminate states.
 *
 * @example
 * <CheckboxField label="Subscribe to newsletter" hint="Max one email per week" onChange={setSubscribed} />
 */
export interface CheckboxFieldProps {
  /** Label text rendered next to the checkbox. */
  label?: string;
  /** Helper text rendered below the checkbox, linked via `aria-describedby`. */
  hint?: string;
  /** Controlled checked state; omit to use uncontrolled mode. */
  checked?: boolean;
  /** Initial checked state in uncontrolled mode. */
  defaultChecked?: boolean;
  /** Visual "partially checked" state (e.g. a parent of a mixed selection). */
  indeterminate?: boolean;
  /**
   * Validation state; `disabled` also disables the input.
   * @default 'default'
   */
  state?: CheckboxFieldState;
  /** Disables the checkbox. */
  disabled?: boolean;
  /** Native form field name. */
  name?: string;
  /**
   * Value submitted with the form when checked.
   * @default 'on'
   */
  value?: string;
  /** Marks the checkbox as required for form submission. */
  required?: boolean;
  /** Called with the next checked state on user interaction. */
  onChange?: (checked: boolean) => void;
  /** Extra class names appended to the root element. */
  className?: string;
  /** Inline styles forwarded to the root element (positioning only — never visual styles). */
  style?: CSSProperties;
  /** Input element id; auto-generated when omitted. */
  id?: string;
}

export function CheckboxField({
  label,
  hint,
  checked,
  defaultChecked,
  indeterminate = false,
  state = 'default',
  disabled,
  name,
  value = 'on',
  required,
  onChange,
  className,
  style,
  id,
}: CheckboxFieldProps) {
  const generatedId = useId();
  const inputId = id ?? generatedId;
  const hintId = `${inputId}-hint`;
  const inputRef = useRef<HTMLInputElement>(null);

  const isControlled = checked !== undefined;
  const isDisabled = disabled || state === 'disabled';
  const isError = state === 'error';
  const isChecked = !!checked;

  useEffect(() => {
    if (inputRef.current) {
      inputRef.current.indeterminate = indeterminate;
    }
  }, [indeterminate]);

  const rootClass = [
    'ui-checkbox-field',
    isError && 'ui-checkbox-field--error',
    isDisabled && 'ui-checkbox-field--disabled',
    isChecked && 'ui-checkbox-field--checked',
    indeterminate && 'ui-checkbox-field--indeterminate',
    className,
  ]
    .filter(Boolean)
    .join(' ');

  return (
    <div className={rootClass} style={style}>
      <label className="ui-checkbox-field__label-row">
        <span className="ui-checkbox-field__box">
          <input
            ref={inputRef}
            id={inputId}
            type="checkbox"
            className="ui-checkbox-field__input"
            {...(isControlled ? { checked } : {})}
            {...(!isControlled && defaultChecked !== undefined ? { defaultChecked } : {})}
            disabled={isDisabled}
            required={required}
            name={name}
            value={value}
            aria-invalid={isError ? 'true' : undefined}
            aria-describedby={hint ? hintId : undefined}
            onChange={(e) => onChange?.(e.target.checked)}
          />
        </span>
        {label && <span className="ui-checkbox-field__label-text">{label}</span>}
      </label>
      {hint && (
        <p id={hintId} className="ui-checkbox-field__hint">
          {hint}
        </p>
      )}
    </div>
  );
}

// packages/web-components/src/checkbox-field/checkbox-field.ts
import { LitElement, html, nothing, type PropertyValues } from 'lit';
import { customElement, property, state } from 'lit/decorators.js';
import { checkboxFieldStyles } from './checkbox-field.styles.js';
import { resetStyles } from '../styles/reset.styles.js';
import { motionStyles } from '../styles/motion.styles.js';

export type CheckboxFieldState = 'default' | 'error' | 'disabled';

/**
 * Form-associated checkbox with label and hint, supporting the indeterminate state.
 *
 * @element ui-checkbox-field
 *
 * @example
 * ```html
 * <ui-checkbox-field label="Subscribe to newsletter" hint="Max one email per week"></ui-checkbox-field>
 * ```
 *
 * @fires {Event} change - Native-like change event after user interaction.
 * @fires {CustomEvent} ui-change - Same moment as `change`; `detail.checked` carries the new state.
 */
@customElement('ui-checkbox-field')
export class UiCheckboxField extends LitElement {
  static readonly formAssociated = true;
  static override shadowRootOptions = { ...LitElement.shadowRootOptions, delegatesFocus: true };
  static override styles = [resetStyles, motionStyles, checkboxFieldStyles];

  /** Label text rendered next to the checkbox. */
  @property({ type: String, reflect: true }) label = '';

  /** Helper text rendered below the checkbox, linked via `aria-describedby`. */
  @property({ type: String, reflect: true }) hint?: string;

  /** Checked state; the attribute also sets the initial state restored on form reset. */
  @property({ type: Boolean, reflect: true }) checked = false;

  /** Visual "partially checked" state (e.g. a parent of a mixed selection). */
  @property({ type: Boolean, reflect: true }) indeterminate = false;

  /**
   * Validation state; `disabled` also disables the input.
   * @default 'default'
   */
  @property({ type: String, reflect: true }) state: CheckboxFieldState = 'default';

  /** Disables the checkbox. */
  @property({ type: Boolean, reflect: true }) disabled = false;

  /** Form field name used on submission. */
  @property({ type: String }) name?: string;

  /**
   * Value submitted with the form when checked.
   * @default 'on'
   */
  @property({ type: String }) value = 'on';

  /** Marks the checkbox as required for form submission. */
  @property({ type: Boolean, reflect: true }) required = false;

  @state() private _formDisabled = false;

  private _defaultChecked = false;
  private _internals: ElementInternals;

  constructor() {
    super();
    this._internals = this.attachInternals();
  }

  override connectedCallback() {
    super.connectedCallback();
    this._defaultChecked = this.checked;
    this._syncFormValue();
  }

  private get _isDisabled(): boolean {
    return this.disabled || this.state === 'disabled' || this._formDisabled;
  }

  protected override updated(changedProperties: PropertyValues<this>): void {
    if (
      changedProperties.has('checked') ||
      changedProperties.has('disabled') ||
      changedProperties.has('state') ||
      changedProperties.has('value')
    ) {
      this._syncFormValue();
    }

    const input = this.shadowRoot?.querySelector<HTMLInputElement>('.input');
    if (input) {
      input.indeterminate = this.indeterminate;
    }
  }

  formDisabledCallback(disabled: boolean) {
    this._formDisabled = disabled;
    this._syncFormValue();
  }

  formResetCallback() {
    this.checked = this._defaultChecked;
    this.indeterminate = false;
  }

  formStateRestoreCallback(state: unknown) {
    this.checked = state === 'checked';
  }

  private _syncFormValue() {
    this._internals.setFormValue(
      this._isDisabled || !this.checked ? null : this.value,
      this.checked ? 'checked' : undefined,
    );
  }

  private _onChange(e: Event): void {
    const input = e.target as HTMLInputElement;
    this.checked = input.checked;
    this.dispatchEvent(new Event('change', { bubbles: true, composed: true }));
    this.dispatchEvent(
      new CustomEvent('ui-change', {
        detail: { checked: this.checked },
        bubbles: true,
        composed: true,
      }),
    );
  }

  override render() {
    const hintId = 'hint';

    return html`
      <label class="label-row">
        <span class="box">
          <input
            class="input"
            type="checkbox"
            .checked=${this.checked}
            ?disabled=${this._isDisabled}
            ?required=${this.required}
            name=${this.name ?? nothing}
            value=${this.value}
            aria-invalid=${this.state === 'error' ? 'true' : nothing}
            aria-describedby=${this.hint ? hintId : nothing}
            @change=${this._onChange}
          />
        </span>
        ${this.label ? html`<span class="label-text">${this.label}</span>` : nothing}
      </label>
      ${this.hint ? html`<p id=${hintId} class="hint">${this.hint}</p>` : nothing}
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'ui-checkbox-field': UiCheckboxField;
  }
}
