// packages/web-components/src/select-field/select-field.ts
import { LitElement, html, nothing, type PropertyValues } from 'lit';
import { customElement, property, state } from 'lit/decorators.js';
import { unsafeSVG } from 'lit/directives/unsafe-svg.js';
import { classMap } from 'lit/directives/class-map.js';
import { svgMap } from '@mszczygiel-projects/ui-core-icons';
import { selectFieldStyles } from './select-field.styles.js';
import { listboxStyles } from '../listbox/listbox.styles.js';
import {
  buildRows,
  firstEnabledRow,
  flattenOptions,
  listboxOptionId,
  nextEnabledRow,
  renderListbox,
  rowIndexOfValue,
  scrollRowIntoView,
} from '../listbox/listbox.js';
import type { ListboxItems, ListboxOption, ListboxRow } from '../listbox/listbox.js';
import { controlFieldStyles } from '../styles/control-field.styles.js';
import { motionStyles } from '../styles/motion.styles.js';
import { resetStyles } from '../styles/reset.styles.js';
import '../popover/popover.js';
import type { PopoverPlacement, PopoverOpenChangeDetail } from '../popover/popover.js';
import { getUiCoreConfig } from '@mszczygiel-projects/ui-core-foundations';

export type SelectFieldVariant = 'outline' | 'filled' | 'underlined';
export type SelectFieldSize = 'small' | 'default' | 'large';
export type SelectFieldState = 'default' | 'success' | 'error' | 'disabled';
export type SelectFieldLabelPlacement = 'top' | 'inner' | 'inline';

/** Single option in a ui-select-field list. */
export type SelectOption = ListboxOption;
/** Named set of options rendered under a sticky header. */
export type { ListboxOptionGroup as SelectOptionGroup } from '../listbox/listbox.js';

const LISTBOX_ID = 'listbox';

/**
 * Form-associated custom dropdown select with keyboard navigation.
 *
 * The list floats through `ui-popover`, so it flips above the field when there
 * is no room below and escapes any `overflow: hidden` ancestor. Options are
 * rendered by the shared listbox module into this component's own shadow root,
 * which is what lets `aria-controls` and `aria-activedescendant` resolve.
 *
 * @element ui-select-field
 *
 * @example
 * ```html
 * <ui-select-field label="Country"></ui-select-field>
 * <script>
 *   document.querySelector('ui-select-field').options = [
 *     { value: 'pl', label: 'Poland' },
 *     { value: 'de', label: 'Germany' },
 *   ];
 * </script>
 * ```
 *
 * @slot leading-icon - Icon rendered inside the trigger, at the start.
 *
 * @fires {Event} input - Native-like input event when the value changes.
 * @fires {Event} change - Native-like change event when the value changes.
 * @fires {CustomEvent} ui-change - Same moment as `change`; `detail.value` carries the selected value.
 *
 * @cssprop --listbox-max-height - Scroll height of the dropdown; falls back to `--select-dropdown-max-height`.
 */
@customElement('ui-select-field')
export class UiSelectField extends LitElement {
  static readonly formAssociated = true;
  static override shadowRootOptions = { ...LitElement.shadowRootOptions, delegatesFocus: true };
  static override styles = [
    resetStyles,
    motionStyles,
    controlFieldStyles,
    listboxStyles,
    selectFieldStyles,
  ];

  /**
   * Container style: bordered, filled background, or bottom border only.
   * @default 'outline'
   */
  @property({ type: String, reflect: true }) variant: SelectFieldVariant = 'outline';

  /**
   * Field height and typography scale.
   * @default 'default'
   */
  @property({ type: String, reflect: true, attribute: 'data-size' }) size: SelectFieldSize =
    'default';

  /**
   * Label position: above the field, stacked inside it, or inline with the
   * value (`Season: 2025/26`).
   * @default 'top'
   */
  @property({ type: String, reflect: true, attribute: 'label-placement' })
  labelPlacement: SelectFieldLabelPlacement = 'top';

  /** Label text. */
  @property({ type: String, reflect: true }) label?: string;

  /** Helper text rendered below the field, linked via `aria-describedby`. */
  @property({ type: String, reflect: true }) hint?: string;

  /**
   * Validation state; `disabled` also disables the trigger.
   * @default 'default'
   */
  @property({ type: String, reflect: true }) state: SelectFieldState = 'default';

  /**
   * Text shown while no option is selected.
   * @default 'Select option...'
   */
  @property({ type: String, reflect: true }) placeholder = 'Select option...';

  /** Selected value; the attribute also sets the initial value restored on form reset. */
  @property({ type: String, reflect: true }) value = '';

  /**
   * Options rendered in the dropdown — a flat array or an array of
   * `{ label, options }` groups. Set as a property, not an attribute.
   */
  @property({ type: Array }) options: ListboxItems = [];

  /**
   * Preferred dropdown position; flips automatically when there is no room.
   * @default 'bottom-start'
   */
  @property({ type: String, reflect: true }) placement: PopoverPlacement = 'bottom-start';

  /** Disables the select. */
  @property({ type: Boolean, reflect: true }) disabled = false;

  /** Shows a clear affordance when a value is selected (also Delete/Backspace). */
  @property({ type: Boolean, reflect: true }) clearable = false;

  /** Form field name used on submission. */
  @property({ type: String }) name?: string;

  /**
   * Text shown when there are no options.
   * @default `getUiCoreConfig().labels.listbox.empty`
   */
  @property({ type: String, attribute: 'empty-label' }) emptyLabel?: string;

  /**
   * Accessible name of the clear button.
   * @default `getUiCoreConfig().labels.selectField.clear`
   */
  @property({ type: String, attribute: 'clear-label' }) clearLabel?: string;

  @state() private _open = false;
  @state() private _activeIndex = -1;
  @state() private _formDisabled = false;

  private _defaultValue = '';
  private _internals: ElementInternals;
  private _triggerResizeObserver?: ResizeObserver;

  constructor() {
    super();
    this._internals = this.attachInternals();
  }

  private get _isDisabled(): boolean {
    return this.disabled || this.state === 'disabled' || this._formDisabled;
  }

  private get _rows(): ListboxRow[] {
    return buildRows(this.options);
  }

  private get _selectedOption(): ListboxOption | undefined {
    return flattenOptions(this.options).find((o) => o.value === this.value);
  }

  private get _triggerEl(): HTMLButtonElement | null {
    return this.shadowRoot?.querySelector<HTMLButtonElement>('.trigger') ?? null;
  }

  override connectedCallback(): void {
    super.connectedCallback();
    this._defaultValue = this.value;
    this._syncFormValue();
  }

  override disconnectedCallback(): void {
    super.disconnectedCallback();
    this._triggerResizeObserver?.disconnect();
    this._triggerResizeObserver = undefined;
  }

  override updated(changedProperties: PropertyValues<this>): void {
    super.updated(changedProperties);
    if (
      changedProperties.has('value') ||
      changedProperties.has('disabled') ||
      changedProperties.has('state')
    ) {
      this._syncFormValue();
    }
    // Cheap when already visible, so no need to diff the active index.
    if (this._open) {
      scrollRowIntoView(this.shadowRoot, LISTBOX_ID, this._activeIndex);
    }
  }

  formDisabledCallback(disabled: boolean): void {
    this._formDisabled = disabled;
  }

  formResetCallback(): void {
    this.value = this._defaultValue;
    this._closeDropdown();
  }

  formStateRestoreCallback(state: FormData | File | string | null): void {
    if (typeof state === 'string') {
      this.value = state;
    }
  }

  private _syncFormValue() {
    this._internals.setFormValue(this._isDisabled ? null : this.value);
  }

  /**
   * Keeps the floating list as wide as the field. Observes the host — a node
   * that survives every re-render — and reads the trigger fresh on each
   * callback, so a re-rendered trigger cannot leave a stale observer behind.
   */
  private _observeTriggerWidth() {
    if (typeof ResizeObserver !== 'function') return;
    const sync = () => {
      const trigger = this._triggerEl;
      if (!trigger) return;
      this.style.setProperty('--_dropdown-width', `${trigger.getBoundingClientRect().width}px`);
    };
    sync();
    this._triggerResizeObserver?.disconnect();
    this._triggerResizeObserver = new ResizeObserver(sync);
    this._triggerResizeObserver.observe(this);
  }

  private _dispatchValueChange() {
    this.dispatchEvent(new Event('input', { bubbles: true, composed: true }));
    this.dispatchEvent(new Event('change', { bubbles: true, composed: true }));
    this.dispatchEvent(
      new CustomEvent('ui-change', {
        detail: { value: this.value },
        bubbles: true,
        composed: true,
      }),
    );
  }

  private _openDropdown() {
    if (this._isDisabled) return;
    this._open = true;
    this.toggleAttribute('open', true);
    const rows = this._rows;
    const selected = rowIndexOfValue(rows, this.value);
    this._activeIndex = selected >= 0 ? selected : firstEnabledRow(rows);
    /*
     * Measure after the render settles: on first open ui-popover may not be
     * upgraded yet, so the trigger would still be shrink-to-fit and the panel
     * would flash at the wrong width.
     */
    void this.updateComplete.then(() => {
      if (this._open) this._observeTriggerWidth();
    });
  }

  private _closeDropdown() {
    this._open = false;
    this.toggleAttribute('open', false);
    this._activeIndex = -1;
    this._triggerResizeObserver?.disconnect();
    this._triggerResizeObserver = undefined;
  }

  private _selectRow(row: ListboxRow) {
    if (row.kind !== 'option' || row.option.disabled) return;
    const prev = this.value;
    this.value = row.option.value;
    this._closeDropdown();
    this._triggerEl?.focus();
    if (prev !== this.value) this._dispatchValueChange();
  }

  private _handleTriggerClick() {
    if (this._open) this._closeDropdown();
    else this._openDropdown();
  }

  private _handlePopoverOpenChange(event: CustomEvent<PopoverOpenChangeDetail>) {
    event.stopPropagation();
    if (!event.detail.open) this._closeDropdown();
  }

  private _handleKeyDown(e: KeyboardEvent) {
    if (this._isDisabled) return;
    const rows = this._rows;

    switch (e.key) {
      case 'Enter':
      case ' ':
        e.preventDefault();
        if (!this._open) this._openDropdown();
        else if (rows[this._activeIndex]) this._selectRow(rows[this._activeIndex]);
        break;
      case 'Escape':
        if (this._open) {
          e.preventDefault();
          this._closeDropdown();
        }
        break;
      case 'ArrowDown':
        e.preventDefault();
        if (!this._open) this._openDropdown();
        else this._activeIndex = nextEnabledRow(rows, this._activeIndex, 1);
        break;
      case 'ArrowUp':
        e.preventDefault();
        if (!this._open) this._openDropdown();
        else this._activeIndex = nextEnabledRow(rows, this._activeIndex, -1);
        break;
      case 'Home':
        if (this._open) {
          e.preventDefault();
          this._activeIndex = firstEnabledRow(rows);
        }
        break;
      case 'End':
        if (this._open) {
          e.preventDefault();
          this._activeIndex = nextEnabledRow(rows, rows.length, -1);
        }
        break;
      case 'Delete':
      case 'Backspace':
        if (!this._open && this.clearable && this.value) {
          e.preventDefault();
          this._handleClear(e);
        }
        break;
      case 'Tab':
        if (this._open) this._closeDropdown();
        break;
    }
  }

  private _handleClear(e: Event) {
    e.stopPropagation();
    e.preventDefault();
    const prev = this.value;
    this.value = '';
    if (prev !== '') this._dispatchValueChange();
  }

  private _handleClearKeyDown(e: KeyboardEvent) {
    if (e.key === 'Enter' || e.key === ' ') this._handleClear(e);
  }

  private _handleLeadingSlotChange(e: Event) {
    const slot = e.target as HTMLSlotElement;
    this.toggleAttribute('has-leading-icon', slot.assignedElements().length > 0);
  }

  override render() {
    const isDisabled = this._isDisabled;
    const selected = this._selectedOption;
    const hasValue = !!this.value;
    const labelId = 'label';
    const triggerId = 'trigger';
    const hintId = 'hint';

    const isInner = this.labelPlacement === 'inner';
    const isInline = this.labelPlacement === 'inline';
    const activeId =
      this._open && this._activeIndex >= 0
        ? listboxOptionId(LISTBOX_ID, this._activeIndex)
        : nothing;

    return html`
      ${this.label && !isInner && !isInline
        ? html`<label id=${labelId} class="label" for=${triggerId}>${this.label}</label>`
        : nothing}
      <div class="field-container">
        <ui-popover
          class="popover"
          trigger="manual"
          placement=${this.placement}
          ?open=${this._open}
          dismiss-on="both"
          @open-change=${this._handlePopoverOpenChange}
        >
          <button
            slot="trigger"
            id=${triggerId}
            class="trigger"
            type="button"
            role="combobox"
            aria-haspopup="listbox"
            aria-expanded=${this._open ? 'true' : 'false'}
            aria-controls=${LISTBOX_ID}
            aria-activedescendant=${activeId}
            aria-describedby=${this.hint ? hintId : nothing}
            aria-labelledby=${this.label ? labelId : nothing}
            ?disabled=${isDisabled}
            @click=${this._handleTriggerClick}
            @keydown=${this._handleKeyDown}
          >
            <slot
              name="leading-icon"
              class="icon icon--leading"
              @slotchange=${this._handleLeadingSlotChange}
            ></slot>
            ${this.label && isInner
              ? html`<span id=${labelId} class="inner-label">${this.label}</span>`
              : nothing}
            <span class="content">
              ${this.label && isInline
                ? html`<span id=${labelId} class="inline-label">${this.label}:</span>`
                : nothing}
              <span
                class=${classMap({
                  value: true,
                  'value--placeholder': !selected,
                })}
              >
                ${selected?.label ?? this.placeholder}
              </span>
            </span>
            <span class="trailing">
              ${this.clearable && hasValue
                ? html`<span
                    class="clear"
                    role="button"
                    aria-label=${this.clearLabel ?? getUiCoreConfig().labels.selectField.clear}
                    tabindex="0"
                    @mousedown=${this._handleClear}
                    @keydown=${this._handleClearKeyDown}
                  >
                    ${unsafeSVG(svgMap['icon-close'])}
                  </span>`
                : nothing}
              <span class="chevron" aria-hidden="true">
                ${this._open
                  ? unsafeSVG(svgMap['icon-chevron-up'])
                  : unsafeSVG(svgMap['icon-chevron-down'])}
              </span>
            </span>
          </button>
          ${this._open
            ? renderListbox({
                idPrefix: LISTBOX_ID,
                items: this.options,
                value: this.value,
                activeIndex: this._activeIndex,
                emptyLabel: this.emptyLabel,
                labelledBy: this.label ? labelId : undefined,
                label: this.label ? undefined : this.placeholder,
                onSelect: (row) => this._selectRow(row),
                onActivate: (index) => {
                  this._activeIndex = index;
                },
              })
            : nothing}
        </ui-popover>
      </div>
      ${this.hint ? html`<p id=${hintId} class="hint">${this.hint}</p>` : nothing}
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'ui-select-field': UiSelectField;
  }
}

// packages/react/src/SelectField/SelectField.tsx
import {
  useCallback,
  useEffect,
  useId,
  useLayoutEffect,
  useRef,
  useState,
  type CSSProperties,
  type ReactNode,
} from 'react';
import {
  IconChevronDown,
  IconChevronUp,
  IconClose,
} from '@mszczygiel-projects/ui-core-icons/react';
import { Popover } from '../Popover/Popover.js';
import type { PopoverPlacement } from '../Popover/Popover.js';
import { Listbox } from '../Listbox/Listbox.js';
import {
  buildRows,
  firstEnabledRow,
  flattenOptions,
  isGroupedItems,
  listboxOptionId,
  nextEnabledRow,
  rowIndexOfValue,
  scrollRowIntoView,
} from '../Listbox/listbox-navigation.js';
import type { ListboxItems, ListboxRow } from '../Listbox/listbox-navigation.js';
import './SelectField.css';
import { getUiCoreConfig } from '@mszczygiel-projects/ui-core-foundations';

export type SelectFieldVariant = 'outline' | 'filled' | 'underlined';
export type SelectFieldSize = 'small' | 'default' | 'large';
export type SelectFieldState = 'default' | 'success' | 'error' | 'disabled';
export type SelectFieldLabelPlacement = 'top' | 'inner' | 'inline';

export type {
  ListboxOption as SelectOption,
  ListboxOptionGroup as SelectOptionGroup,
} from '../Listbox/listbox-navigation.js';

/**
 * Custom dropdown select with keyboard navigation and a hidden native select
 * for form submission.
 *
 * The list floats through `Popover`, so it flips above the field when there is
 * no room below and escapes any `overflow: hidden` ancestor.
 *
 * @example
 * <SelectField
 *   label="Country"
 *   options={[{ value: 'pl', label: 'Poland' }, { value: 'de', label: 'Germany' }]}
 *   onChange={setCountry}
 * />
 */
export interface SelectFieldProps {
  /**
   * Container style: bordered, filled background, or bottom border only.
   * @default 'outline'
   */
  variant?: SelectFieldVariant;
  /**
   * Field height and typography scale.
   * @default 'default'
   */
  size?: SelectFieldSize;
  /**
   * Label position: above the field, stacked inside it, or inline with the
   * value (`Season: 2025/26`).
   * @default 'top'
   */
  labelPlacement?: SelectFieldLabelPlacement;
  /** Trigger element id; auto-generated when omitted. */
  id?: string;
  /** Label text. */
  label?: string;
  /** Helper text rendered below the field, linked via `aria-describedby`. */
  hint?: string;
  /**
   * Validation state; `disabled` also disables the trigger.
   * @default 'default'
   */
  state?: SelectFieldState;
  /**
   * Text shown while no option is selected.
   * @default 'Select option...'
   */
  placeholder?: string;
  /** Controlled selected value; omit to use uncontrolled mode. */
  value?: string;
  /** Initially selected value in uncontrolled mode. */
  defaultValue?: string;
  /**
   * Options rendered in the dropdown — a flat array or an array of
   * `{ label, options }` groups.
   * @default []
   */
  options?: ListboxItems;
  /**
   * Preferred dropdown position; flips automatically when there is no room.
   * @default 'bottom-start'
   */
  placement?: PopoverPlacement;
  /** Disables the select. */
  disabled?: boolean;
  /** Shows a clear affordance when a value is selected (also Delete/Backspace). */
  clearable?: boolean;
  /** Native form field name — enables the hidden native select for form submission. */
  name?: string;
  /** Marks the select as required for form submission. */
  required?: boolean;
  /** Associates the hidden native select with a form by id. */
  form?: string;
  /** Autocomplete hint forwarded to the hidden native select. */
  autoComplete?: string;
  /** Sets `aria-invalid` on the trigger. */
  ariaInvalid?: boolean;
  /** Icon rendered inside the trigger, at the start. */
  leadingIcon?: ReactNode;
  /**
   * Text shown when there are no options.
   * @default `getUiCoreConfig().labels.listbox.empty`
   */
  emptyLabel?: string;
  /**
   * Accessible name of the clear button.
   * @default `getUiCoreConfig().labels.selectField.clear`
   */
  clearLabel?: string;
  /** Called with the selected option's value; clearing passes an empty string. */
  onChange?: (value: string) => void;
  /** Extra class names appended to the root element. */
  className?: string;
  /** Inline styles forwarded to the root element (positioning only — never visual styles). */
  style?: CSSProperties;
}

export function SelectField({
  variant = 'outline',
  size = 'default',
  labelPlacement = 'top',
  id,
  label,
  hint,
  state = 'default',
  placeholder = 'Select option...',
  value,
  defaultValue,
  options = [],
  placement = 'bottom-start',
  disabled,
  clearable = false,
  name,
  required = false,
  form,
  autoComplete,
  ariaInvalid,
  leadingIcon,
  emptyLabel,
  clearLabel,
  onChange,
  className,
  style,
}: SelectFieldProps) {
  const generatedId = useId();
  const triggerId = id ?? `${generatedId}-trigger`;
  const labelId = `${triggerId}-label`;
  const listboxId = `${triggerId}-listbox`;
  const hintId = `${triggerId}-hint`;

  const isControlled = value !== undefined;
  const initialUncontrolledValueRef = useRef(defaultValue ?? '');
  const [internalValue, setInternalValue] = useState(() => defaultValue ?? '');
  const effectiveValue = isControlled ? value : internalValue;

  const [open, setOpen] = useState(false);
  const [activeIndex, setActiveIndex] = useState(-1);

  const wrapperRef = useRef<HTMLDivElement>(null);
  const triggerRef = useRef<HTMLButtonElement>(null);

  const isDisabled = disabled || state === 'disabled';
  const flatOptions = flattenOptions(options);
  const rows = buildRows(options);
  const selectedOption = flatOptions.find((o) => o.value === effectiveValue);
  const hasValue = !!effectiveValue;

  /*
   * Keeps the floating list as wide as the field. Observes the wrapper — a node
   * React never recreates — and reads the trigger fresh on each callback, so a
   * re-rendered trigger cannot leave a stale observer behind.
   */
  useLayoutEffect(() => {
    const wrapper = wrapperRef.current;
    if (!open || !wrapper) return undefined;
    const sync = () => {
      const trigger = triggerRef.current;
      if (!trigger) return;
      wrapper.style.setProperty(
        '--ui-select-field-dropdown-width',
        `${trigger.getBoundingClientRect().width}px`,
      );
    };
    sync();
    if (typeof ResizeObserver !== 'function') return undefined;
    const observer = new ResizeObserver(sync);
    observer.observe(wrapper);
    return () => observer.disconnect();
  }, [open]);

  // Keeps the active row visible while arrowing through a scrolling list.
  useEffect(() => {
    if (!open) return;
    scrollRowIntoView(listboxId, activeIndex);
  }, [open, activeIndex, listboxId]);

  useEffect(() => {
    const formElement = wrapperRef.current?.closest('form');
    if (!formElement) return;

    const handleFormReset = () => {
      setOpen(false);
      setActiveIndex(-1);
      if (!isControlled) {
        setInternalValue(initialUncontrolledValueRef.current);
      }
    };

    formElement.addEventListener('reset', handleFormReset);
    return () => formElement.removeEventListener('reset', handleFormReset);
  }, [isControlled]);

  const closeDropdown = useCallback(() => {
    setOpen(false);
    setActiveIndex(-1);
  }, []);

  const openDropdown = () => {
    if (isDisabled) return;
    setOpen(true);
    const selected = rowIndexOfValue(rows, effectiveValue);
    setActiveIndex(selected >= 0 ? selected : firstEnabledRow(rows));
  };

  const handleSelect = (row: ListboxRow) => {
    if (row.kind !== 'option' || row.option.disabled) return;
    const prev = effectiveValue;
    if (!isControlled) setInternalValue(row.option.value);
    closeDropdown();
    triggerRef.current?.focus();
    if (prev !== row.option.value) onChange?.(row.option.value);
  };

  const handleClear = (e: React.SyntheticEvent | Event) => {
    e.stopPropagation();
    e.preventDefault();
    if (!isControlled) setInternalValue('');
    if (effectiveValue !== '') onChange?.('');
  };

  const handleNativeSelectChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    const nextValue = e.target.value;
    if (!isControlled) setInternalValue(nextValue);
    if (effectiveValue !== nextValue) onChange?.(nextValue);
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (isDisabled) return;

    switch (e.key) {
      case 'Enter':
      case ' ':
        e.preventDefault();
        if (!open) openDropdown();
        else if (rows[activeIndex]) handleSelect(rows[activeIndex]);
        break;
      case 'Escape':
        if (open) {
          e.preventDefault();
          closeDropdown();
        }
        break;
      case 'ArrowDown':
        e.preventDefault();
        if (!open) openDropdown();
        else setActiveIndex((i) => nextEnabledRow(rows, i, 1));
        break;
      case 'ArrowUp':
        e.preventDefault();
        if (!open) openDropdown();
        else setActiveIndex((i) => nextEnabledRow(rows, i, -1));
        break;
      case 'Home':
        if (open) {
          e.preventDefault();
          setActiveIndex(firstEnabledRow(rows));
        }
        break;
      case 'End':
        if (open) {
          e.preventDefault();
          setActiveIndex(nextEnabledRow(rows, rows.length, -1));
        }
        break;
      case 'Delete':
      case 'Backspace':
        if (!open && clearable && effectiveValue) {
          e.preventDefault();
          handleClear(e);
        }
        break;
      case 'Tab':
        if (open) closeDropdown();
        break;
    }
  };

  const isInner = labelPlacement === 'inner';
  const isInline = labelPlacement === 'inline';

  const rootClass = [
    'ui-select-field',
    // Shared size ramp and per-variant colour aliases.
    'ui-control-field',
    `ui-control-field--${variant}`,
    size !== 'default' && `ui-control-field--${size}`,
    `ui-select-field--${variant}`,
    size !== 'default' && `ui-select-field--${size}`,
    open && 'ui-select-field--open',
    state !== 'default' && `ui-select-field--state-${state}`,
    leadingIcon && 'ui-select-field--has-leading-icon',
    isInner && 'ui-select-field--inner',
    isInline && 'ui-select-field--inline',
    className,
  ]
    .filter(Boolean)
    .join(' ');

  const trigger = (
    <button
      ref={triggerRef}
      id={triggerId}
      className="ui-select-field__trigger"
      type="button"
      role="combobox"
      aria-haspopup="listbox"
      aria-expanded={open}
      aria-controls={listboxId}
      aria-activedescendant={
        open && activeIndex >= 0 ? listboxOptionId(listboxId, activeIndex) : undefined
      }
      aria-describedby={hint ? hintId : undefined}
      aria-labelledby={label ? labelId : undefined}
      aria-required={required || undefined}
      aria-invalid={ariaInvalid || undefined}
      disabled={isDisabled}
      onClick={() => (open ? closeDropdown() : openDropdown())}
      onKeyDown={handleKeyDown}
    >
      {leadingIcon && (
        <span className="ui-select-field__leading-icon" aria-hidden="true">
          {leadingIcon}
        </span>
      )}
      {label && isInner && (
        <span id={labelId} className="ui-select-field__inner-label">
          {label}
        </span>
      )}
      <span className="ui-select-field__content">
        {label && isInline && (
          <span id={labelId} className="ui-select-field__inline-label">
            {label}:
          </span>
        )}
        <span
          className={[
            'ui-select-field__value',
            !selectedOption && 'ui-select-field__value--placeholder',
          ]
            .filter(Boolean)
            .join(' ')}
        >
          {selectedOption?.label ?? placeholder}
        </span>
      </span>
      <span className="ui-select-field__trailing">
        {clearable && hasValue && (
          <span
            className="ui-select-field__clear"
            role="button"
            aria-label={clearLabel ?? getUiCoreConfig().labels.selectField.clear}
            tabIndex={0}
            onMouseDown={handleClear}
            onKeyDown={(e) => {
              if (e.key === 'Enter' || e.key === ' ') handleClear(e);
            }}
          >
            <IconClose />
          </span>
        )}
        <span className="ui-select-field__chevron" aria-hidden="true">
          {open ? <IconChevronUp /> : <IconChevronDown />}
        </span>
      </span>
    </button>
  );

  return (
    <div className={rootClass} ref={wrapperRef} style={style}>
      {label && !isInner && !isInline && (
        <label id={labelId} className="ui-select-field__label" htmlFor={triggerId}>
          {label}
        </label>
      )}
      <div className="ui-select-field__field-container">
        <Popover
          className="ui-select-field__popover"
          trigger="manual"
          placement={placement}
          open={open}
          onOpenChange={(detail) => {
            if (!detail.open) closeDropdown();
          }}
          anchor={trigger}
        >
          {/* Mounted only while open: the popover panel stays in the DOM either way. */}
          {open && (
            <Listbox
              idPrefix={listboxId}
              items={options}
              value={effectiveValue}
              activeIndex={activeIndex}
              size={size}
              emptyLabel={emptyLabel}
              labelledBy={label ? labelId : undefined}
              label={label ? undefined : placeholder}
              onSelect={handleSelect}
              onActivate={setActiveIndex}
            />
          )}
        </Popover>
        {name && (
          <select
            className="ui-select-field__native-select"
            tabIndex={-1}
            aria-hidden="true"
            name={name}
            value={effectiveValue}
            required={required}
            form={form}
            autoComplete={autoComplete}
            disabled={isDisabled}
            onChange={handleNativeSelectChange}
          >
            <option value="" disabled={required}>
              {placeholder}
            </option>
            {isGroupedItems(options)
              ? options.map((group) => (
                  <optgroup key={group.label} label={group.label}>
                    {(group.options ?? []).map((opt) => (
                      <option key={opt.value} value={opt.value} disabled={opt.disabled}>
                        {opt.label}
                      </option>
                    ))}
                  </optgroup>
                ))
              : flatOptions.map((opt) => (
                  <option key={opt.value} value={opt.value} disabled={opt.disabled}>
                    {opt.label}
                  </option>
                ))}
          </select>
        )}
      </div>
      {hint && (
        <p id={hintId} className="ui-select-field__hint">
          {hint}
        </p>
      )}
    </div>
  );
}
