// packages/web-components/src/button/button.ts
import { LitElement, html, nothing } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { buttonStyles } from './button.styles.js';
import { focusStyles } from '../styles/focus.styles.js';
import { resetStyles } from '../styles/reset.styles.js';
import '../loader/loader.js';

export type ButtonVariant = 'primary' | 'secondary' | 'outline' | 'ghost' | 'danger';
export type ButtonSize = 'small' | 'default' | 'large';

@customElement('ui-button')
export class UiButton extends LitElement {
  static override shadowRootOptions = { ...LitElement.shadowRootOptions, delegatesFocus: true };
  static override styles = [resetStyles, focusStyles, buttonStyles];

  @property({ type: String, reflect: true }) variant: ButtonVariant = 'primary';
  @property({ type: String, reflect: true, attribute: 'data-size' }) size: ButtonSize = 'default';
  @property({ type: Boolean, reflect: true }) loading = false;
  @property({ type: Boolean }) disabled = false;
  @property({ type: String }) type: 'button' | 'submit' | 'reset' = 'button';
  @property({ type: String }) label?: string;

  private get loaderSize(): 'small' | 'default' {
    return this.size === 'large' ? 'default' : 'small';
  }

  override render() {
    return html`
      <button
        type=${this.type}
        ?disabled=${this.disabled || this.loading}
        aria-busy=${this.loading ? 'true' : nothing}
        aria-label=${this.label ?? nothing}
      >
        ${this.loading
          ? html`<ui-loader data-size=${this.loaderSize} label="Loading"></ui-loader>`
          : html`<slot name="icon-left"></slot>`}
        <span class="label"><slot></slot></span>
        ${this.loading ? nothing : html`<slot name="icon-right"></slot>`}
      </button>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'ui-button': UiButton;
  }
}

// packages/react/src/button/Button.tsx
import type { CSSProperties, ReactNode } from 'react';
import { Loader } from '../Loader/Loader.js';
import './Button.css';

export type ButtonVariant = 'primary' | 'secondary' | 'outline' | 'ghost' | 'danger';
export type ButtonSize = 'small' | 'default' | 'large';

export interface ButtonProps {
  variant?: ButtonVariant;
  size?: ButtonSize;
  loading?: boolean;
  disabled?: boolean;
  type?: 'button' | 'submit' | 'reset';
  iconLeft?: ReactNode;
  iconRight?: ReactNode;
  children?: ReactNode;
  onClick?: React.MouseEventHandler<HTMLButtonElement>;
  className?: string;
  style?: CSSProperties;
  'aria-label'?: string;
}

export function Button({
  variant = 'primary',
  size = 'default',
  loading = false,
  disabled = false,
  type = 'button',
  iconLeft,
  iconRight,
  children,
  onClick,
  className,
  style,
  'aria-label': ariaLabel,
}: ButtonProps) {
  const loaderSize = size === 'large' ? 'default' : 'small';

  return (
    <button
      type={type}
      disabled={disabled || loading}
      aria-busy={loading ? 'true' : undefined}
      aria-label={ariaLabel}
      onClick={onClick}
      className={[
        'ui-button',
        `ui-button--${variant}`,
        size !== 'default' && `ui-button--${size}`,
        loading && 'ui-button--loading',
        className,
      ]
        .filter(Boolean)
        .join(' ')}
      style={style}
    >
      {loading ? (
        <Loader size={loaderSize} label="Loading" />
      ) : (
        iconLeft && <span className="ui-button__icon">{iconLeft}</span>
      )}
      <span className="ui-button__label">{children}</span>
      {!loading && iconRight && <span className="ui-button__icon">{iconRight}</span>}
    </button>
  );
}
