// packages/react/src/RadioField/RadioField.tsx
import { useId, type CSSProperties } from 'react';
import './RadioField.css';

export type RadioFieldState = 'default' | 'error' | 'disabled';

/**
 * Single radio button with label and hint; group radios by giving them the same `name`.
 *
 * @example
 * <RadioField name="plan" value="pro" label="Pro plan" onChange={selectPro} />
 */
export interface RadioFieldProps {
  /** Label text rendered next to the radio. */
  label?: string;
  /** Helper text rendered below the radio, linked via `aria-describedby`. */
  hint?: string;
  /** Controlled checked state; omit to use uncontrolled mode. */
  checked?: boolean;
  /** Initial checked state in uncontrolled mode. */
  defaultChecked?: boolean;
  /**
   * Validation state; `disabled` also disables the input.
   * @default 'default'
   */
  state?: RadioFieldState;
  /** Disables the radio. */
  disabled?: boolean;
  /** Native form field name — radios with the same name form a group. */
  name?: string;
  /**
   * Value submitted with the form when selected.
   * @default 'on'
   */
  value?: string;
  /** Marks the radio group as required for form submission. */
  required?: boolean;
  /** Called with the next checked state on user interaction. */
  onChange?: (checked: boolean) => void;
  /** Extra class names appended to the root element. */
  className?: string;
  /** Inline styles forwarded to the root element (positioning only — never visual styles). */
  style?: CSSProperties;
  /** Input element id; auto-generated when omitted. */
  id?: string;
}

export function RadioField({
  label,
  hint,
  checked,
  defaultChecked,
  state = 'default',
  disabled,
  name,
  value = 'on',
  required,
  onChange,
  className,
  style,
  id,
}: RadioFieldProps) {
  const generatedId = useId();
  const inputId = id ?? generatedId;
  const hintId = `${inputId}-hint`;

  const isControlled = checked !== undefined;
  const isDisabled = disabled || state === 'disabled';
  const isError = state === 'error';
  const isChecked = !!checked;

  const rootClass = [
    'ui-radio-field',
    isError && 'ui-radio-field--error',
    isDisabled && 'ui-radio-field--disabled',
    isChecked && 'ui-radio-field--checked',
    className,
  ]
    .filter(Boolean)
    .join(' ');

  return (
    <div className={rootClass} style={style}>
      <label className="ui-radio-field__label-row">
        <span className="ui-radio-field__control">
          <input
            id={inputId}
            type="radio"
            className="ui-radio-field__input"
            {...(isControlled ? { checked } : {})}
            {...(!isControlled && defaultChecked !== undefined ? { defaultChecked } : {})}
            disabled={isDisabled}
            required={required}
            name={name}
            value={value}
            aria-invalid={isError ? 'true' : undefined}
            aria-describedby={hint ? hintId : undefined}
            onChange={(e) => onChange?.(e.target.checked)}
          />
        </span>
        {label && <span className="ui-radio-field__label-text">{label}</span>}
      </label>
      {hint && (
        <p id={hintId} className="ui-radio-field__hint">
          {hint}
        </p>
      )}
    </div>
  );
}

// packages/web-components/src/radio-field/radio-field.ts
import { LitElement, html, nothing, type PropertyValues } from 'lit';
import { customElement, property, state } from 'lit/decorators.js';
import { radioFieldStyles } from './radio-field.styles.js';
import { resetStyles } from '../styles/reset.styles.js';
import { motionStyles } from '../styles/motion.styles.js';

export type RadioFieldState = 'default' | 'error' | 'disabled';

/**
 * Form-associated single radio button with label and hint; group radios by giving them the same `name`.
 *
 * @element ui-radio-field
 *
 * @example
 * ```html
 * <ui-radio-field name="plan" value="pro" label="Pro plan"></ui-radio-field>
 * ```
 *
 * @fires {Event} change - Native-like change event after user interaction.
 * @fires {CustomEvent} ui-change - Same moment as `change`; `detail.checked` carries the new state.
 */
@customElement('ui-radio-field')
export class UiRadioField extends LitElement {
  static readonly formAssociated = true;
  static override shadowRootOptions = { ...LitElement.shadowRootOptions, delegatesFocus: true };
  static override styles = [resetStyles, motionStyles, radioFieldStyles];

  /** Label text rendered next to the radio. */
  @property({ type: String, reflect: true }) label = '';

  /** Helper text rendered below the radio, linked via `aria-describedby`. */
  @property({ type: String, reflect: true }) hint?: string;

  /** Checked state; the attribute also sets the initial state restored on form reset. */
  @property({ type: Boolean, reflect: true }) checked = false;

  /**
   * Validation state; `disabled` also disables the input.
   * @default 'default'
   */
  @property({ type: String, reflect: true }) state: RadioFieldState = 'default';

  /** Disables the radio. */
  @property({ type: Boolean, reflect: true }) disabled = false;

  /** Form field name — radios with the same name form a group. */
  @property({ type: String }) name?: string;

  /**
   * Value submitted with the form when selected.
   * @default 'on'
   */
  @property({ type: String }) value = 'on';

  /** Marks the radio group as required for form submission. */
  @property({ type: Boolean, reflect: true }) required = false;

  @state() private _formDisabled = false;

  private _defaultChecked = false;
  private _internals: ElementInternals;

  constructor() {
    super();
    this._internals = this.attachInternals();
  }

  override connectedCallback() {
    super.connectedCallback();
    this._defaultChecked = this.checked;
    this._syncFormValue();
  }

  private get _isDisabled(): boolean {
    return this.disabled || this.state === 'disabled' || this._formDisabled;
  }

  protected override updated(changedProperties: PropertyValues<this>): void {
    if (
      changedProperties.has('checked') ||
      changedProperties.has('disabled') ||
      changedProperties.has('state') ||
      changedProperties.has('value')
    ) {
      this._syncFormValue();
    }
  }

  formDisabledCallback(disabled: boolean) {
    this._formDisabled = disabled;
    this._syncFormValue();
  }

  formResetCallback() {
    this.checked = this._defaultChecked;
  }

  formStateRestoreCallback(state: unknown) {
    this.checked = state === 'checked';
  }

  private _syncFormValue() {
    this._internals.setFormValue(
      this._isDisabled || !this.checked ? null : this.value,
      this.checked ? 'checked' : undefined,
    );
  }

  private _onChange(e: Event): void {
    const input = e.target as HTMLInputElement;
    this.checked = input.checked;
    this.dispatchEvent(new Event('change', { bubbles: true, composed: true }));
    this.dispatchEvent(
      new CustomEvent('ui-change', {
        detail: { checked: this.checked },
        bubbles: true,
        composed: true,
      }),
    );
  }

  override render() {
    const hintId = 'hint';

    return html`
      <label class="label-row">
        <span class="control">
          <input
            class="input"
            type="radio"
            .checked=${this.checked}
            ?disabled=${this._isDisabled}
            ?required=${this.required}
            name=${this.name ?? nothing}
            value=${this.value}
            aria-invalid=${this.state === 'error' ? 'true' : nothing}
            aria-describedby=${this.hint ? hintId : nothing}
            @change=${this._onChange}
          />
        </span>
        ${this.label ? html`<span class="label-text">${this.label}</span>` : nothing}
      </label>
      ${this.hint ? html`<p id=${hintId} class="hint">${this.hint}</p>` : nothing}
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'ui-radio-field': UiRadioField;
  }
}
