// packages/react/src/Combobox/Combobox.tsx
import {
  useCallback,
  useEffect,
  useId,
  useLayoutEffect,
  useMemo,
  useRef,
  useState,
  type CSSProperties,
  type KeyboardEvent as ReactKeyboardEvent,
  type ReactNode,
} from 'react';
import {
  IconChevronDown,
  IconChevronUp,
  IconClose,
} from '@mszczygiel-projects/ui-core-icons/react';
import { Popover } from '../Popover/Popover.js';
import type { PopoverPlacement } from '../Popover/Popover.js';
import { Chip } from '../Chip/Chip.js';
import { Listbox } from '../Listbox/Listbox.js';
import {
  buildRows,
  firstEnabledRow,
  flattenOptions,
  isGroupedItems,
  listboxOptionId,
  nextEnabledRow,
  rowIndexOfValue,
  scrollRowIntoView,
  toggleValue,
} from '../Listbox/listbox-navigation.js';
import type { ListboxItems, ListboxOption, ListboxRow } from '../Listbox/listbox-navigation.js';
import './Combobox.css';
import { getUiCoreConfig } from '@mszczygiel-projects/ui-core-foundations';

export type ComboboxVariant = 'outline' | 'filled' | 'underlined';
export type ComboboxSize = 'small' | 'default' | 'large';
export type ComboboxState = 'default' | 'success' | 'error' | 'disabled';

/** Where the option list comes from: filtered here, or supplied pre-filtered. */
export type ComboboxFilterMode = 'local' | 'remote';

export type {
  ListboxOption as ComboboxOption,
  ListboxOptionGroup as ComboboxOptionGroup,
} from '../Listbox/listbox-navigation.js';

const DEFAULT_FILTER_DEBOUNCE_MS = 200;

/**
 * Text input that filters a large option list as you type.
 *
 * Implements the WAI-ARIA combobox pattern: the input itself carries
 * `role="combobox"` with `aria-expanded`, `aria-controls` and
 * `aria-activedescendant`, and focus never leaves it while navigating.
 *
 * @example
 * <Combobox
 *   label="Season"
 *   options={[{ value: '2025', label: '2025/26' }]}
 *   value={value}
 *   onChange={setValue}
 * />
 */
export interface ComboboxProps {
  /**
   * Container style: bordered, filled background, or bottom border only.
   * @default 'outline'
   */
  variant?: ComboboxVariant;
  /**
   * Field height and typography scale.
   * @default 'default'
   */
  size?: ComboboxSize;
  /**
   * Validation state; `disabled` also disables the input.
   * @default 'default'
   */
  state?: ComboboxState;
  /** Input element id; auto-generated when omitted. */
  id?: string;
  /** Label text rendered above the field. */
  label?: string;
  /** Helper text rendered below the field, linked via `aria-describedby`. */
  hint?: string;
  /**
   * Text shown in the empty input.
   * @default 'Search...'
   */
  placeholder?: string;
  /** Selected value in single mode. */
  value?: string;
  /** Selected values in `multiple` mode. */
  values?: string[];
  /**
   * Allows selecting more than one option, shown as chips inside the field.
   * @default false
   */
  multiple?: boolean;
  /**
   * Options to choose from — a flat array or an array of `{ label, options }` groups.
   * @default []
   */
  options?: ListboxItems;
  /**
   * `local` filters `options` by label; `remote` renders them as given and
   * calls `onFilter` so the consumer can fetch.
   * @default 'local'
   */
  filterMode?: ComboboxFilterMode;
  /** Shows the loading message in place of the list. */
  loading?: boolean;
  /** Offers a "create" row when the query matches no option. */
  allowCreate?: boolean;
  /**
   * Delay before `onFilter` fires, in ms.
   * @default 200
   */
  filterDebounce?: number;
  /**
   * Preferred dropdown position; flips automatically when there is no room.
   * @default 'bottom-start'
   */
  placement?: PopoverPlacement;
  /** Disables the combobox. */
  disabled?: boolean;
  /** Shows a clear affordance once there is a selection or a query. */
  clearable?: boolean;
  /** Icon rendered inside the field, at the start. */
  leadingIcon?: ReactNode;
  /**
   * Text shown when nothing matches.
   * @default `getUiCoreConfig().labels.listbox.empty`
   */
  emptyLabel?: string;
  /**
   * Accessible name of the clear button.
   * @default `getUiCoreConfig().labels.combobox.clear`
   */
  clearLabel?: string;
  /**
   * Builds the accessible name of a selected chip's dismiss button, in `multiple` mode.
   * @default `getUiCoreConfig().labels.combobox.removeChip`
   */
  removeChipLabel?: (optionLabel: string) => string;
  /**
   * Text shown while `loading`.
   * @default `getUiCoreConfig().labels.listbox.loading`
   */
  loadingLabel?: string;
  /**
   * Prefix of the create row; the query is appended in quotes.
   * @default `getUiCoreConfig().labels.listbox.create`
   */
  createLabel?: string;
  /** Called with the selected value in single mode. */
  onChange?: (value: string) => void;
  /** Called with the full selection in `multiple` mode. */
  onValuesChange?: (values: string[]) => void;
  /** Called with the debounced query — drive remote fetching from here. */
  onFilter?: (query: string) => void;
  /** Called when the create affordance is chosen, with the raw query. */
  onCreate?: (label: string) => void;
  /** Extra class names appended to the root element. */
  className?: string;
  /** Inline styles forwarded to the root element (positioning only — never visual styles). */
  style?: CSSProperties;
}

export function Combobox({
  variant = 'outline',
  size = 'default',
  state = 'default',
  id,
  label,
  hint,
  placeholder = 'Search...',
  value = '',
  values = [],
  multiple = false,
  options = [],
  filterMode = 'local',
  loading = false,
  allowCreate = false,
  filterDebounce = DEFAULT_FILTER_DEBOUNCE_MS,
  placement = 'bottom-start',
  disabled,
  clearable = false,
  leadingIcon,
  emptyLabel,
  loadingLabel,
  createLabel,
  clearLabel,
  removeChipLabel,
  onChange,
  onValuesChange,
  onFilter,
  onCreate,
  className,
  style,
}: ComboboxProps) {
  const generatedId = useId();
  const inputId = id ?? `${generatedId}-input`;
  const labelId = `${inputId}-label`;
  const listboxId = `${inputId}-listbox`;
  const hintId = `${inputId}-hint`;

  const [open, setOpen] = useState(false);
  const [query, setQuery] = useState('');
  const [activeIndex, setActiveIndex] = useState(-1);

  const wrapperRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);
  const filterTimer = useRef<ReturnType<typeof setTimeout>>();

  const isDisabled = disabled || state === 'disabled';

  /** Options after local filtering; remote mode trusts what it was given. */
  const visibleOptions = useMemo<ListboxItems>(() => {
    const needle = query.trim().toLowerCase();
    if (filterMode === 'remote' || !needle) return options;
    const matches = (option: ListboxOption) => option.label.toLowerCase().includes(needle);
    if (isGroupedItems(options)) {
      return options
        .map((group) => ({ ...group, options: (group.options ?? []).filter(matches) }))
        .filter((group) => group.options.length > 0);
    }
    return (options as ListboxOption[]).filter(matches);
  }, [options, query, filterMode]);

  /** Query offered by the create row, or undefined when it does not apply. */
  const createQuery = useMemo(() => {
    const trimmed = query.trim();
    if (!allowCreate || !trimmed) return undefined;
    const exists = flattenOptions(options).some(
      (option) => option.label.toLowerCase() === trimmed.toLowerCase(),
    );
    return exists ? undefined : trimmed;
  }, [allowCreate, query, options]);

  const rows = useMemo(() => buildRows(visibleOptions, createQuery), [visibleOptions, createQuery]);

  const selectedOptions = useMemo(() => {
    const all = flattenOptions(options);
    return values
      .map((v) => all.find((o) => o.value === v))
      .filter((o): o is ListboxOption => Boolean(o));
  }, [options, values]);

  const selectedOption = useMemo(
    () => flattenOptions(options).find((o) => o.value === value),
    [options, value],
  );

  /* Keeps the floating list as wide as the field. Observes the wrapper — a node
   * React never recreates — and reads the field fresh on each callback. */
  useLayoutEffect(() => {
    const wrapper = wrapperRef.current;
    if (!open || !wrapper) return undefined;
    const sync = () => {
      const field = wrapper.querySelector<HTMLElement>('.ui-combobox__field');
      if (!field) return;
      wrapper.style.setProperty(
        '--ui-combobox-dropdown-width',
        `${field.getBoundingClientRect().width}px`,
      );
    };
    sync();
    if (typeof ResizeObserver !== 'function') return undefined;
    const observer = new ResizeObserver(sync);
    observer.observe(wrapper);
    return () => observer.disconnect();
  }, [open]);

  useEffect(() => {
    if (!open) return;
    scrollRowIntoView(listboxId, activeIndex);
  }, [open, activeIndex, listboxId]);

  useEffect(() => () => clearTimeout(filterTimer.current), []);

  const openList = useCallback(() => {
    if (isDisabled) return;
    setOpen(true);
  }, [isDisabled]);

  const closeList = useCallback(() => {
    setOpen(false);
    setActiveIndex(-1);
  }, []);

  const handleInput = (event: React.ChangeEvent<HTMLInputElement>) => {
    const next = event.target.value;
    setQuery(next);
    openList();
    setActiveIndex(0);
    clearTimeout(filterTimer.current);
    filterTimer.current = setTimeout(() => onFilter?.(next), filterDebounce);
  };

  const handleSelect = (row: ListboxRow) => {
    if (row.kind === 'create') {
      onCreate?.(query.trim());
      setQuery('');
      closeList();
      inputRef.current?.focus();
      return;
    }
    if (row.option.disabled) return;

    if (multiple) {
      onValuesChange?.(toggleValue(values, row.option.value));
      setQuery('');
      /*
       * The list stays open so more options can be picked. Clearing the query
       * re-expands the list, so the highlight has to be re-found by value —
       * keeping the old index would silently move it to a different option,
       * and resetting it would throw the user back to the top of the list.
       */
      const nextRows = buildRows(options);
      const index = rowIndexOfValue(nextRows, row.option.value);
      setActiveIndex(index >= 0 ? index : firstEnabledRow(nextRows));
    } else {
      onChange?.(row.option.value);
      setQuery('');
      closeList();
    }
    inputRef.current?.focus();
  };

  const removeValue = (optionValue: string) => {
    if (isDisabled) return;
    onValuesChange?.(values.filter((v) => v !== optionValue));
    inputRef.current?.focus();
  };

  const handleClear = (event: React.SyntheticEvent) => {
    event.stopPropagation();
    event.preventDefault();
    setQuery('');
    if (multiple) onValuesChange?.([]);
    else onChange?.('');
    inputRef.current?.focus();
  };

  const handleKeyDown = (event: ReactKeyboardEvent<HTMLInputElement>) => {
    if (isDisabled) return;

    switch (event.key) {
      case 'ArrowDown':
        event.preventDefault();
        if (!open) {
          openList();
          setActiveIndex(firstEnabledRow(rows));
        } else setActiveIndex((i) => nextEnabledRow(rows, i, 1));
        break;
      case 'ArrowUp':
        event.preventDefault();
        if (!open) {
          openList();
          setActiveIndex(firstEnabledRow(rows));
        } else setActiveIndex((i) => nextEnabledRow(rows, i, -1));
        break;
      case 'Home':
        if (open) {
          event.preventDefault();
          setActiveIndex(firstEnabledRow(rows));
        }
        break;
      case 'End':
        if (open) {
          event.preventDefault();
          setActiveIndex(nextEnabledRow(rows, rows.length, -1));
        }
        break;
      case 'Enter':
        if (open && rows[activeIndex]) {
          event.preventDefault();
          handleSelect(rows[activeIndex]);
        }
        break;
      case 'Escape':
        if (open) {
          event.preventDefault();
          closeList();
        }
        break;
      case 'Backspace':
        // Empty query: peel the last chip, the usual multi-select shortcut.
        if (multiple && query === '' && values.length > 0) {
          removeValue(values[values.length - 1]);
        }
        break;
      case 'Tab':
        if (open) closeList();
        break;
    }
  };

  /*
   * Opens on pointer and keyboard interaction rather than on focus: selecting
   * an option refocuses the input, and a focus-to-open rule would immediately
   * reopen the list the selection just closed.
   */
  const handleFieldClick = () => {
    inputRef.current?.focus();
    if (!open) {
      openList();
      setActiveIndex(firstEnabledRow(rows));
    }
  };

  const hasSelection = multiple ? values.length > 0 : value !== '';
  const inputValue = query || (multiple ? '' : (selectedOption?.label ?? ''));

  const rootClass = [
    'ui-combobox',
    // Shared size ramp and per-variant colour aliases.
    'ui-control-field',
    `ui-control-field--${variant}`,
    size !== 'default' && `ui-control-field--${size}`,
    `ui-combobox--${variant}`,
    size !== 'default' && `ui-combobox--${size}`,
    open && 'ui-combobox--open',
    state !== 'default' && `ui-combobox--state-${state}`,
    leadingIcon && 'ui-combobox--has-leading-icon',
    multiple && 'ui-combobox--multiple',
    className,
  ]
    .filter(Boolean)
    .join(' ');

  const field = (
    /*
     * Clicking anywhere in the box focuses the input, which is the real control
     * — the box itself carries no role and needs no keyboard handler of its own.
     */
    <div className="ui-combobox__field" onClick={handleFieldClick}>
      {leadingIcon && (
        <span className="ui-combobox__leading-icon" aria-hidden="true">
          {leadingIcon}
        </span>
      )}
      <div className="ui-combobox__content">
        {multiple && selectedOptions.length > 0 && (
          <div className="ui-combobox__chips">
            {selectedOptions.map((option) => (
              <Chip
                key={option.value}
                appearance="subtle"
                size="small"
                dismissible
                disabled={isDisabled}
                dismissLabel={(removeChipLabel ?? getUiCoreConfig().labels.combobox.removeChip)(
                  option.label,
                )}
                onDismiss={() => removeValue(option.value)}
              >
                {option.label}
              </Chip>
            ))}
          </div>
        )}
        <input
          ref={inputRef}
          id={inputId}
          className="ui-combobox__input"
          type="text"
          role="combobox"
          autoComplete="off"
          spellCheck={false}
          aria-autocomplete="list"
          aria-expanded={open}
          aria-controls={listboxId}
          aria-activedescendant={
            open && activeIndex >= 0 ? listboxOptionId(listboxId, activeIndex) : undefined
          }
          aria-describedby={hint ? hintId : undefined}
          aria-labelledby={label ? labelId : undefined}
          placeholder={multiple && hasSelection ? '' : placeholder}
          value={inputValue}
          disabled={isDisabled}
          onChange={handleInput}
          onKeyDown={handleKeyDown}
        />
      </div>
      <span className="ui-combobox__trailing">
        {clearable && (hasSelection || query) && (
          <span
            className="ui-combobox__clear"
            role="button"
            aria-label={clearLabel ?? getUiCoreConfig().labels.combobox.clear}
            tabIndex={0}
            onMouseDown={handleClear}
            onKeyDown={(e) => {
              if (e.key === 'Enter' || e.key === ' ') handleClear(e);
            }}
          >
            <IconClose />
          </span>
        )}
        <span className="ui-combobox__chevron" aria-hidden="true">
          {open ? <IconChevronUp /> : <IconChevronDown />}
        </span>
      </span>
    </div>
  );

  return (
    <div className={rootClass} ref={wrapperRef} style={style}>
      {label && (
        <label id={labelId} className="ui-combobox__label" htmlFor={inputId}>
          {label}
        </label>
      )}
      <div className="ui-combobox__field-container">
        <Popover
          className="ui-combobox__popover"
          trigger="manual"
          placement={placement}
          open={open}
          onOpenChange={(detail) => {
            if (!detail.open) closeList();
          }}
          anchor={field}
        >
          {/* Mounted only while open: the popover panel stays in the DOM either way. */}
          {open && (
            <Listbox
              idPrefix={listboxId}
              items={visibleOptions}
              value={multiple ? values : value}
              multiple={multiple}
              activeIndex={activeIndex}
              size={size}
              loading={loading}
              loadingLabel={loadingLabel}
              emptyLabel={emptyLabel}
              createLabel={createLabel}
              createValue={createQuery}
              labelledBy={label ? labelId : undefined}
              label={label ? undefined : placeholder}
              onSelect={handleSelect}
              onActivate={setActiveIndex}
            />
          )}
        </Popover>
      </div>
      {hint && (
        <p id={hintId} className="ui-combobox__hint">
          {hint}
        </p>
      )}
    </div>
  );
}

// packages/web-components/src/combobox/combobox.ts
import { LitElement, html, nothing, type PropertyValues } from 'lit';
import { customElement, property, query, state } from 'lit/decorators.js';
import { unsafeSVG } from 'lit/directives/unsafe-svg.js';
import { repeat } from 'lit/directives/repeat.js';
import { svgMap } from '@mszczygiel-projects/ui-core-icons';
import { comboboxStyles } from './combobox.styles.js';
import { listboxStyles } from '../listbox/listbox.styles.js';
import {
  buildRows,
  firstEnabledRow,
  flattenOptions,
  isGroupedItems,
  listboxOptionId,
  nextEnabledRow,
  renderListbox,
  rowIndexOfValue,
  scrollRowIntoView,
  toggleValue,
} from '../listbox/listbox.js';
import type { ListboxItems, ListboxOption, ListboxRow } from '../listbox/listbox.js';
import { controlFieldStyles } from '../styles/control-field.styles.js';
import { motionStyles } from '../styles/motion.styles.js';
import { resetStyles } from '../styles/reset.styles.js';
import '../popover/popover.js';
import '../chip/chip.js';
import type { PopoverPlacement, PopoverOpenChangeDetail } from '../popover/popover.js';
import { getUiCoreConfig } from '@mszczygiel-projects/ui-core-foundations';

export type ComboboxVariant = 'outline' | 'filled' | 'underlined';
export type ComboboxSize = 'small' | 'default' | 'large';
export type ComboboxState = 'default' | 'success' | 'error' | 'disabled';

/** Where the option list comes from: filtered here, or supplied pre-filtered. */
export type ComboboxFilterMode = 'local' | 'remote';

export interface ComboboxChangeDetail {
  /** Selected value in single mode; empty string when cleared. */
  value: string;
  /** Selected values in `multiple` mode. */
  values: string[];
}

export interface ComboboxFilterDetail {
  /** Current query text, debounced. */
  query: string;
}

export interface ComboboxCreateDetail {
  /** Query text the user asked to turn into a new option. */
  label: string;
}

const LISTBOX_ID = 'listbox';
const DEFAULT_FILTER_DEBOUNCE_MS = 200;

/**
 * Text input that filters a large option list as you type.
 *
 * Implements the WAI-ARIA combobox pattern: the input itself carries
 * `role="combobox"` with `aria-expanded`, `aria-controls` and
 * `aria-activedescendant`, while focus never leaves it. Options come from the
 * shared listbox module rendered into this component's own shadow root, which
 * is what lets those id references resolve.
 *
 * @element ui-combobox
 *
 * @example
 * ```html
 * <ui-combobox label="Season" placeholder="Search seasons"></ui-combobox>
 * <script>
 *   const el = document.querySelector('ui-combobox');
 *   el.options = [
 *     { value: '2025', label: '2025/26' },
 *     { value: '2024', label: '2024/25' },
 *   ];
 *   el.addEventListener('ui-change', (e) => console.log(e.detail.value));
 * </script>
 * ```
 *
 * @slot leading-icon - Icon rendered inside the field, at the start.
 *
 * @fires {CustomEvent} ui-change - Selection changed; `detail: { value, values }`.
 * @fires {CustomEvent} ui-filter - Debounced query change, for `filter-mode="remote"`; `detail: { query }`.
 * @fires {CustomEvent} ui-create - Create affordance chosen; `detail: { label }`.
 *
 * @cssprop --listbox-max-height - Scroll height of the dropdown; falls back to `--select-dropdown-max-height`.
 */
@customElement('ui-combobox')
export class UiCombobox extends LitElement {
  static readonly formAssociated = true;
  static override shadowRootOptions = { ...LitElement.shadowRootOptions, delegatesFocus: true };
  static override styles = [
    resetStyles,
    motionStyles,
    controlFieldStyles,
    listboxStyles,
    comboboxStyles,
  ];

  /**
   * Container style: bordered, filled background, or bottom border only.
   * @default 'outline'
   */
  @property({ type: String, reflect: true }) variant: ComboboxVariant = 'outline';

  /**
   * Field height and typography scale.
   * @default 'default'
   */
  @property({ type: String, reflect: true, attribute: 'data-size' }) size: ComboboxSize = 'default';

  /**
   * Validation state; `disabled` also disables the input.
   * @default 'default'
   */
  @property({ type: String, reflect: true }) state: ComboboxState = 'default';

  /** Label text rendered above the field. */
  @property({ type: String, reflect: true }) label?: string;

  /** Helper text rendered below the field, linked via `aria-describedby`. */
  @property({ type: String, reflect: true }) hint?: string;

  /** Text shown in the empty input. */
  @property({ type: String, reflect: true }) placeholder = 'Search...';

  /** Selected value in single mode. */
  @property({ type: String, reflect: true }) value = '';

  /** Selected values in `multiple` mode — set as a property, not an attribute. */
  @property({ type: Array }) values: string[] = [];

  /** Allows selecting more than one option, shown as chips inside the field. */
  @property({ type: Boolean, reflect: true }) multiple = false;

  /** Options to choose from — a flat array or an array of `{ label, options }` groups. */
  @property({ type: Array }) options: ListboxItems = [];

  /**
   * `local` filters `options` by label; `remote` renders them as given and
   * emits `ui-filter` so the consumer can fetch.
   * @default 'local'
   */
  @property({ type: String, reflect: true, attribute: 'filter-mode' })
  filterMode: ComboboxFilterMode = 'local';

  /** Shows the loading message in place of the list. */
  @property({ type: Boolean, reflect: true }) loading = false;

  /** Offers a "create" row when the query matches no option. */
  @property({ type: Boolean, reflect: true, attribute: 'allow-create' }) allowCreate = false;

  /**
   * Delay before `ui-filter` fires, in ms.
   * @default 200
   */
  @property({ type: Number, attribute: 'filter-debounce' })
  filterDebounce = DEFAULT_FILTER_DEBOUNCE_MS;

  /**
   * Preferred dropdown position; flips automatically when there is no room.
   * @default 'bottom-start'
   */
  @property({ type: String, reflect: true }) placement: PopoverPlacement = 'bottom-start';

  /** Disables the combobox. */
  @property({ type: Boolean, reflect: true }) disabled = false;

  /** Shows a clear affordance once there is a selection or a query. */
  @property({ type: Boolean, reflect: true }) clearable = false;

  /** Form field name used on submission. */
  @property({ type: String }) name?: string;

  /**
   * Text shown when nothing matches.
   * @default `getUiCoreConfig().labels.listbox.empty`
   */
  @property({ type: String, attribute: 'empty-label' }) emptyLabel?: string;

  /**
   * Accessible name of the clear button.
   * @default `getUiCoreConfig().labels.combobox.clear`
   */
  @property({ type: String, attribute: 'clear-label' }) clearLabel?: string;

  /**
   * Builds the accessible name of a selected chip's dismiss button, in `multiple`
   * mode. Property-only (function type).
   * @default `getUiCoreConfig().labels.combobox.removeChip`
   */
  @property({ attribute: false }) removeChipLabel?: (optionLabel: string) => string;

  /**
   * Text shown while `loading`.
   * @default `getUiCoreConfig().labels.listbox.loading`
   */
  @property({ type: String, attribute: 'loading-label' }) loadingLabel?: string;

  /**
   * Prefix of the create row; the query is appended in quotes.
   * @default `getUiCoreConfig().labels.listbox.create`
   */
  @property({ type: String, attribute: 'create-label' }) createLabel?: string;

  @state() private _open = false;
  @state() private _query = '';
  @state() private _activeIndex = -1;
  @state() private _formDisabled = false;

  @query('.input') private _inputEl?: HTMLInputElement;

  private _internals: ElementInternals;
  private _resizeObserver?: ResizeObserver;
  private _filterTimer?: ReturnType<typeof setTimeout>;
  private _defaultValue = '';
  private _defaultValues: string[] = [];

  constructor() {
    super();
    this._internals = this.attachInternals();
  }

  private get _isDisabled(): boolean {
    return this.disabled || this.state === 'disabled' || this._formDisabled;
  }

  /** Options after local filtering; remote mode trusts what it was given. */
  private get _visibleOptions(): ListboxItems {
    const query = this._query.trim().toLowerCase();
    if (this.filterMode === 'remote' || !query) return this.options;

    const matches = (option: ListboxOption) => option.label.toLowerCase().includes(query);

    if (isGroupedItems(this.options)) {
      return this.options
        .map((group) => ({ ...group, options: (group.options ?? []).filter(matches) }))
        .filter((group) => group.options.length > 0);
    }
    return (this.options as ListboxOption[]).filter(matches);
  }

  /** Query offered by the create row, or undefined when it does not apply. */
  private get _createQuery(): string | undefined {
    const query = this._query.trim();
    if (!this.allowCreate || !query) return undefined;
    const exists = flattenOptions(this.options).some(
      (option) => option.label.toLowerCase() === query.toLowerCase(),
    );
    return exists ? undefined : query;
  }

  private get _rows(): ListboxRow[] {
    return buildRows(this._visibleOptions, this._createQuery);
  }

  private get _selectedOptions(): ListboxOption[] {
    const all = flattenOptions(this.options);
    return this.values
      .map((v) => all.find((o) => o.value === v))
      .filter(Boolean) as ListboxOption[];
  }

  private get _selectedOption(): ListboxOption | undefined {
    return flattenOptions(this.options).find((o) => o.value === this.value);
  }

  override connectedCallback(): void {
    super.connectedCallback();
    this._defaultValue = this.value;
    this._defaultValues = [...this.values];
    this._syncFormValue();
  }

  override disconnectedCallback(): void {
    super.disconnectedCallback();
    this._resizeObserver?.disconnect();
    this._resizeObserver = undefined;
    clearTimeout(this._filterTimer);
  }

  override updated(changed: PropertyValues<this>): void {
    super.updated(changed);
    if (
      changed.has('value') ||
      changed.has('values') ||
      changed.has('disabled') ||
      changed.has('state')
    ) {
      this._syncFormValue();
    }
    if (this._open) {
      scrollRowIntoView(this.shadowRoot, LISTBOX_ID, this._activeIndex);
    }
  }

  formDisabledCallback(disabled: boolean): void {
    this._formDisabled = disabled;
  }

  formResetCallback(): void {
    this.value = this._defaultValue;
    this.values = [...this._defaultValues];
    this._query = '';
    this._close();
  }

  formStateRestoreCallback(state: FormData | File | string | null): void {
    if (typeof state === 'string') this.value = state;
  }

  private _syncFormValue() {
    if (this._isDisabled) {
      this._internals.setFormValue(null);
      return;
    }
    if (this.multiple) {
      const data = new FormData();
      if (this.name) for (const v of this.values) data.append(this.name, v);
      this._internals.setFormValue(data);
    } else {
      this._internals.setFormValue(this.value);
    }
  }

  private _dispatchChange() {
    this.dispatchEvent(new Event('input', { bubbles: true, composed: true }));
    this.dispatchEvent(new Event('change', { bubbles: true, composed: true }));
    this.dispatchEvent(
      new CustomEvent<ComboboxChangeDetail>('ui-change', {
        detail: { value: this.value, values: [...this.values] },
        bubbles: true,
        composed: true,
      }),
    );
  }

  /**
   * Keeps the floating list as wide as the field. Observes the host — a node
   * that survives every re-render — and reads the field fresh on each callback.
   */
  private _observeFieldWidth() {
    if (typeof ResizeObserver !== 'function') return;
    const sync = () => {
      const field = this.shadowRoot?.querySelector<HTMLElement>('.field');
      if (!field) return;
      this.style.setProperty('--_dropdown-width', `${field.getBoundingClientRect().width}px`);
    };
    sync();
    this._resizeObserver?.disconnect();
    this._resizeObserver = new ResizeObserver(sync);
    this._resizeObserver.observe(this);
  }

  private _open_() {
    if (this._isDisabled || this._open) return;
    this._open = true;
    this.toggleAttribute('open', true);
    this._activeIndex = firstEnabledRow(this._rows);
    void this.updateComplete.then(() => {
      if (this._open) this._observeFieldWidth();
    });
  }

  private _close() {
    this._open = false;
    this.toggleAttribute('open', false);
    this._activeIndex = -1;
    this._resizeObserver?.disconnect();
    this._resizeObserver = undefined;
  }

  private _scheduleFilterEvent() {
    clearTimeout(this._filterTimer);
    this._filterTimer = setTimeout(() => {
      this.dispatchEvent(
        new CustomEvent<ComboboxFilterDetail>('ui-filter', {
          detail: { query: this._query },
          bubbles: true,
          composed: true,
        }),
      );
    }, this.filterDebounce);
  }

  private _handleInput(event: Event) {
    const input = event.target as HTMLInputElement;
    this._query = input.value;
    this._open_();
    this._activeIndex = firstEnabledRow(this._rows);
    this._scheduleFilterEvent();
  }

  private _selectRow(row: ListboxRow) {
    if (row.kind === 'create') {
      const label = this._query.trim();
      this.dispatchEvent(
        new CustomEvent<ComboboxCreateDetail>('ui-create', {
          detail: { label },
          bubbles: true,
          composed: true,
        }),
      );
      this._query = '';
      this._close();
      this._inputEl?.focus();
      return;
    }

    if (row.option.disabled) return;

    if (this.multiple) {
      this.values = toggleValue(this.values, row.option.value);
      this._query = '';
      /*
       * The list stays open so more options can be picked. Clearing the query
       * re-expands the list, so the highlight has to be re-found by value —
       * keeping the old index would silently move it to a different option,
       * and resetting it would throw the user back to the top of the list.
       */
      const rows = this._rows;
      const index = rowIndexOfValue(rows, row.option.value);
      this._activeIndex = index >= 0 ? index : firstEnabledRow(rows);
    } else {
      this.value = row.option.value;
      this._query = '';
      this._close();
    }
    this._inputEl?.focus();
    this._dispatchChange();
  }

  private _removeValue(value: string) {
    if (this._isDisabled) return;
    this.values = this.values.filter((v) => v !== value);
    this._dispatchChange();
    this._inputEl?.focus();
  }

  private _handleClear(event: Event) {
    event.stopPropagation();
    event.preventDefault();
    const had = this.multiple ? this.values.length > 0 : this.value !== '';
    this.value = '';
    this.values = [];
    this._query = '';
    if (had) this._dispatchChange();
    this._inputEl?.focus();
  }

  private _handleKeyDown(event: KeyboardEvent) {
    if (this._isDisabled) return;
    const rows = this._rows;

    switch (event.key) {
      case 'ArrowDown':
        event.preventDefault();
        if (!this._open) this._open_();
        else this._activeIndex = nextEnabledRow(rows, this._activeIndex, 1);
        break;
      case 'ArrowUp':
        event.preventDefault();
        if (!this._open) this._open_();
        else this._activeIndex = nextEnabledRow(rows, this._activeIndex, -1);
        break;
      case 'Home':
        if (this._open) {
          event.preventDefault();
          this._activeIndex = firstEnabledRow(rows);
        }
        break;
      case 'End':
        if (this._open) {
          event.preventDefault();
          this._activeIndex = nextEnabledRow(rows, rows.length, -1);
        }
        break;
      case 'Enter':
        if (this._open && rows[this._activeIndex]) {
          event.preventDefault();
          this._selectRow(rows[this._activeIndex]);
        }
        break;
      case 'Escape':
        if (this._open) {
          event.preventDefault();
          this._close();
        }
        break;
      case 'Backspace':
        // Empty query: peel the last chip, the usual multi-select shortcut.
        if (this.multiple && this._query === '' && this.values.length > 0) {
          this._removeValue(this.values[this.values.length - 1]);
        }
        break;
      case 'Tab':
        if (this._open) this._close();
        break;
    }
  }

  /*
   * Opens on pointer and keyboard interaction rather than on focus: selecting
   * an option refocuses the input, and a focus-to-open rule would immediately
   * reopen the list the selection just closed. It also stops the list from
   * popping open while tabbing through a form.
   */
  private _handleFieldClick() {
    this._inputEl?.focus();
    this._open_();
  }

  private _handlePopoverOpenChange(event: CustomEvent<PopoverOpenChangeDetail>) {
    event.stopPropagation();
    if (!event.detail.open) this._close();
  }

  private _handleLeadingSlotChange(event: Event) {
    const slot = event.target as HTMLSlotElement;
    this.toggleAttribute('has-leading-icon', slot.assignedElements().length > 0);
  }

  /** Input text: the live query while typing, otherwise the selected label. */
  private get _inputValue(): string {
    if (this._query) return this._query;
    if (this.multiple) return '';
    return this._selectedOption?.label ?? '';
  }

  override render() {
    const isDisabled = this._isDisabled;
    const labelId = 'label';
    const inputId = 'input';
    const hintId = 'hint';
    const hasSelection = this.multiple ? this.values.length > 0 : this.value !== '';
    const activeId =
      this._open && this._activeIndex >= 0
        ? listboxOptionId(LISTBOX_ID, this._activeIndex)
        : nothing;

    return html`
      ${this.label
        ? html`<label id=${labelId} class="label" for=${inputId}>${this.label}</label>`
        : nothing}
      <div class="field-container">
        <ui-popover
          class="popover"
          trigger="manual"
          placement=${this.placement}
          ?open=${this._open}
          dismiss-on="both"
          @open-change=${this._handlePopoverOpenChange}
        >
          <div slot="trigger" class="field" @click=${this._handleFieldClick}>
            <slot
              name="leading-icon"
              class="icon icon--leading"
              @slotchange=${this._handleLeadingSlotChange}
            ></slot>
            <div class="content">
              ${this.multiple
                ? html`<div class="chips">
                    ${repeat(
                      this._selectedOptions,
                      (option) => option.value,
                      (option) => html`
                        <ui-chip
                          appearance="subtle"
                          data-size="small"
                          dismissible
                          ?disabled=${isDisabled}
                          dismiss-label=${(
                            this.removeChipLabel ?? getUiCoreConfig().labels.combobox.removeChip
                          )(option.label)}
                          @dismiss=${() => this._removeValue(option.value)}
                          >${option.label}</ui-chip
                        >
                      `,
                    )}
                  </div>`
                : nothing}
              <input
                id=${inputId}
                class="input"
                type="text"
                role="combobox"
                autocomplete="off"
                spellcheck="false"
                aria-autocomplete="list"
                aria-expanded=${this._open ? 'true' : 'false'}
                aria-controls=${LISTBOX_ID}
                aria-activedescendant=${activeId}
                aria-describedby=${this.hint ? hintId : nothing}
                aria-labelledby=${this.label ? labelId : nothing}
                placeholder=${this.multiple && hasSelection ? '' : this.placeholder}
                .value=${this._inputValue}
                ?disabled=${isDisabled}
                @input=${this._handleInput}
                @keydown=${this._handleKeyDown}
              />
            </div>
            <span class="trailing">
              ${this.clearable && (hasSelection || this._query)
                ? html`<span
                    class="clear"
                    role="button"
                    aria-label=${this.clearLabel ?? getUiCoreConfig().labels.combobox.clear}
                    tabindex="0"
                    @mousedown=${this._handleClear}
                    @keydown=${(e: KeyboardEvent) => {
                      if (e.key === 'Enter' || e.key === ' ') this._handleClear(e);
                    }}
                  >
                    ${unsafeSVG(svgMap['icon-close'])}
                  </span>`
                : nothing}
              <span class="chevron" aria-hidden="true">
                ${this._open
                  ? unsafeSVG(svgMap['icon-chevron-up'])
                  : unsafeSVG(svgMap['icon-chevron-down'])}
              </span>
            </span>
          </div>
          ${this._open
            ? renderListbox({
                idPrefix: LISTBOX_ID,
                items: this._visibleOptions,
                value: this.multiple ? this.values : this.value,
                multiple: this.multiple,
                activeIndex: this._activeIndex,
                loading: this.loading,
                loadingLabel: this.loadingLabel,
                emptyLabel: this.emptyLabel,
                createLabel: this.createLabel,
                createValue: this._createQuery,
                labelledBy: this.label ? labelId : undefined,
                label: this.label ? undefined : this.placeholder,
                onSelect: (row) => this._selectRow(row),
                onActivate: (index) => {
                  this._activeIndex = index;
                },
              })
            : nothing}
        </ui-popover>
      </div>
      ${this.hint ? html`<p id=${hintId} class="hint">${this.hint}</p>` : nothing}
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'ui-combobox': UiCombobox;
  }
}
