// packages/react/src/TextField/TextField.tsx
import {
  forwardRef,
  useId,
  type CSSProperties,
  type ReactNode,
  type InputHTMLAttributes,
} from 'react';
import { IconDanger } from '@mszczygiel-projects/ui-core-icons/react';
import './TextField.css';

export type TextFieldVariant = 'outline' | 'filled' | 'underlined';
export type TextFieldSize = 'small' | 'default' | 'large';
export type TextFieldState = 'default' | 'success' | 'error' | 'disabled';
export type TextFieldLabelPlacement = 'top' | 'floating' | 'inner';

/**
 * Single-line text input with label, hint, validation states, and optional icons.
 *
 * @example
 * <TextField label="Email" type="email" hint="Work address preferred" onChange={setEmail} />
 */
export interface TextFieldProps extends Omit<
  InputHTMLAttributes<HTMLInputElement>,
  'size' | 'onChange'
> {
  /**
   * Container style: bordered, filled background, or bottom border only.
   * @default 'outline'
   */
  variant?: TextFieldVariant;
  /**
   * Field height and typography scale.
   * @default 'default'
   */
  size?: TextFieldSize;
  /** Label text. */
  label?: string;
  /**
   * Label position: above the field, floating over it, or inline inside it.
   * @default 'top'
   */
  labelPlacement?: TextFieldLabelPlacement;
  /** Helper text rendered below the field, linked via `aria-describedby`. */
  hint?: string;
  /**
   * Validation state; `error` shows a danger icon, `disabled` also disables the input.
   * @default 'default'
   */
  state?: TextFieldState;
  /** Icon rendered inside the field, at the start. */
  leadingIcon?: ReactNode;
  /** Icon rendered inside the field, at the end; `error` state provides a default. */
  trailingIcon?: ReactNode;
  /** Called with the input's string value on every change. */
  onChange?: (value: string) => void;
  /** Extra class names appended to the root element. */
  className?: string;
  /** Inline styles forwarded to the root element (positioning only — never visual styles). */
  style?: CSSProperties;
}

export const TextField = forwardRef<HTMLInputElement, TextFieldProps>(function TextField(
  {
    variant = 'outline',
    size = 'default',
    label,
    labelPlacement = 'top',
    placeholder = '',
    value,
    hint,
    state = 'default',
    leadingIcon,
    trailingIcon,
    onChange,
    name,
    type = 'text',
    disabled,
    required,
    readOnly,
    className,
    style,
    ...inputProps
  }: TextFieldProps,
  ref,
) {
  const generatedId = useId();
  const inputId = inputProps.id ?? generatedId;
  const hintId = `${inputId}-hint`;
  const isControlled = value !== undefined;

  const isDisabled = disabled || state === 'disabled';
  const effectiveTrailingIcon = trailingIcon ?? (state === 'error' ? <IconDanger /> : undefined);

  const isFloating = labelPlacement === 'floating';
  const isInner = labelPlacement === 'inner';

  const rootClass = [
    'ui-text-field',
    `ui-text-field--${variant}`,
    size !== 'default' && `ui-text-field--${size}`,
    isFloating && 'ui-text-field--floating',
    isInner && 'ui-text-field--inner',
    state !== 'default' && `ui-text-field--state-${state}`,
    leadingIcon && 'ui-text-field--has-leading-icon',
    effectiveTrailingIcon && 'ui-text-field--has-trailing-icon',
    className,
  ]
    .filter(Boolean)
    .join(' ');

  const labelEl = label ? (
    <label className="ui-text-field__label" htmlFor={inputId}>
      {label}
    </label>
  ) : null;

  return (
    <div className={rootClass} style={style}>
      {!isFloating && !isInner && labelEl}
      <div className="ui-text-field__field-wrapper">
        {isInner && labelEl}
        {leadingIcon && (
          <span className="ui-text-field__icon ui-text-field__icon--leading">{leadingIcon}</span>
        )}
        <input
          {...inputProps}
          id={inputId}
          ref={ref}
          className="ui-text-field__input"
          type={type}
          name={name}
          {...(isControlled ? { value } : {})}
          placeholder={isFloating ? ' ' : placeholder}
          disabled={isDisabled}
          required={required}
          readOnly={readOnly}
          aria-invalid={state === 'error' ? 'true' : undefined}
          aria-required={required ? 'true' : undefined}
          aria-describedby={hint ? hintId : undefined}
          onChange={(e) => onChange?.(e.target.value)}
        />
        {isFloating && labelEl}
        {effectiveTrailingIcon && (
          <span className="ui-text-field__icon ui-text-field__icon--trailing">
            {effectiveTrailingIcon}
          </span>
        )}
      </div>
      {hint && (
        <p id={hintId} className="ui-text-field__hint">
          {hint}
        </p>
      )}
    </div>
  );
});

// packages/web-components/src/text-field/text-field.ts
import { LitElement, html, nothing, type PropertyValues } from 'lit';
import { customElement, property, state } from 'lit/decorators.js';
import { unsafeSVG } from 'lit/directives/unsafe-svg.js';
import { svgMap } from '@mszczygiel-projects/ui-core-icons';
import { textFieldStyles } from './text-field.styles.js';
import { motionStyles } from '../styles/motion.styles.js';
import { resetStyles } from '../styles/reset.styles.js';

export type TextFieldVariant = 'outline' | 'filled' | 'underlined';
export type TextFieldSize = 'small' | 'default' | 'large';
export type TextFieldState = 'default' | 'success' | 'error' | 'disabled';
export type TextFieldLabelPlacement = 'top' | 'floating' | 'inner';

/**
 * Form-associated single-line text input with label, hint, validation states, and icon slots.
 *
 * @element ui-text-field
 *
 * @example
 * ```html
 * <ui-text-field label="Email" type="email" hint="Work address preferred"></ui-text-field>
 * ```
 *
 * @slot leading-icon - Icon rendered inside the field, at the start.
 * @slot trailing-icon - Icon rendered inside the field, at the end; `error` state provides a default.
 *
 * @fires {Event} input - Native-like input event on every keystroke.
 * @fires {CustomEvent} ui-input - Same moment as `input`; `detail.value` carries the current value.
 * @fires {Event} change - Native-like change event when the value is committed.
 * @fires {CustomEvent} ui-change - Same moment as `change`; `detail.value` carries the current value.
 */
@customElement('ui-text-field')
export class UiTextField extends LitElement {
  static readonly formAssociated = true;
  static override shadowRootOptions = { ...LitElement.shadowRootOptions, delegatesFocus: true };
  static override styles = [resetStyles, motionStyles, textFieldStyles];

  /**
   * Container style: bordered, filled background, or bottom border only.
   * @default 'outline'
   */
  @property({ type: String, reflect: true }) variant: TextFieldVariant = 'outline';

  /**
   * Field height and typography scale.
   * @default 'default'
   */
  @property({ type: String, reflect: true, attribute: 'data-size' }) size: TextFieldSize =
    'default';

  /** Label text. */
  @property({ type: String, reflect: true }) label?: string;

  /**
   * Label position: above the field, floating over it, or inline inside it.
   * @default 'top'
   */
  @property({ type: String, reflect: true, attribute: 'label-placement' })
  labelPlacement: TextFieldLabelPlacement = 'top';

  /** Placeholder text shown while empty. */
  @property({ type: String, reflect: true }) placeholder = '';

  /** Current value; the attribute also sets the initial value restored on form reset. */
  @property({ type: String, reflect: true }) value = '';

  /** Helper text rendered below the field, linked via `aria-describedby`. */
  @property({ type: String, reflect: true }) hint?: string;

  /**
   * Validation state; `error` shows a danger icon, `disabled` also disables the input.
   * @default 'default'
   */
  @property({ type: String, reflect: true }) state: TextFieldState = 'default';

  /** Form field name used on submission. */
  @property({ type: String }) name?: string;

  /**
   * Native input type.
   * @default 'text'
   */
  @property({ type: String }) type: 'text' | 'email' | 'tel' | 'url' = 'text';

  /** Disables the input. */
  @property({ type: Boolean, reflect: true }) disabled = false;

  /** Marks the field as required for form submission. */
  @property({ type: Boolean, reflect: true }) required = false;

  /** Makes the input read-only. */
  @property({ type: Boolean, reflect: true }) readonly = false;

  @state() private _hasLeadingIcon = false;
  @state() private _hasTrailingIcon = false;
  @state() private _formDisabled = false;

  private _defaultValue = '';
  private _internals: ElementInternals;

  constructor() {
    super();
    this._internals = this.attachInternals();
  }

  override connectedCallback() {
    super.connectedCallback();
    this._defaultValue = this.value;
    this._syncFormValue();
  }

  private get _isFloating(): boolean {
    return this.labelPlacement === 'floating';
  }

  private get _isInner(): boolean {
    return this.labelPlacement === 'inner';
  }

  private get _isDisabled(): boolean {
    return this.disabled || this.state === 'disabled' || this._formDisabled;
  }

  private get _showsErrorTrailingIcon(): boolean {
    return this.state === 'error' && !this._hasTrailingIcon;
  }

  protected override updated(changedProperties: PropertyValues<this>): void {
    if (
      changedProperties.has('value') ||
      changedProperties.has('disabled') ||
      changedProperties.has('state')
    ) {
      this._syncFormValue();
    }
    this.toggleAttribute('has-leading-icon', this._hasLeadingIcon);
    this.toggleAttribute(
      'has-trailing-icon',
      this._hasTrailingIcon || this._showsErrorTrailingIcon,
    );
  }

  formDisabledCallback(disabled: boolean) {
    this._formDisabled = disabled;
    this._syncFormValue();
  }

  formResetCallback() {
    this.value = this._defaultValue;
  }

  formStateRestoreCallback(state: unknown) {
    if (typeof state === 'string') this.value = state;
  }

  private _syncFormValue() {
    this._internals.setFormValue(this._isDisabled ? null : this.value);
  }

  private _onLeadingSlotChange(e: Event) {
    const slot = e.target as HTMLSlotElement;
    this._hasLeadingIcon = slot.assignedElements().length > 0;
  }

  private _onTrailingSlotChange(e: Event) {
    const slot = e.target as HTMLSlotElement;
    this._hasTrailingIcon = slot.assignedElements().length > 0;
  }

  private _onInput(e: Event) {
    const input = e.target as HTMLInputElement;
    this.value = input.value;
    this.dispatchEvent(new Event('input', { bubbles: true, composed: true }));
    this.dispatchEvent(
      new CustomEvent('ui-input', { detail: { value: this.value }, bubbles: true, composed: true }),
    );
  }

  private _onChange(e: Event) {
    const input = e.target as HTMLInputElement;
    this.value = input.value;
    this.dispatchEvent(new Event('change', { bubbles: true, composed: true }));
    this.dispatchEvent(
      new CustomEvent('ui-change', {
        detail: { value: this.value },
        bubbles: true,
        composed: true,
      }),
    );
  }

  override render() {
    const isFloating = this._isFloating;
    const isInner = this._isInner;
    const isDisabled = this._isDisabled;
    const hintId = 'hint';

    return html`
      ${!isFloating && !isInner && this.label
        ? html`<label class="label" for="input">${this.label}</label>`
        : nothing}
      <div class="field-wrapper">
        ${isInner && this.label
          ? html`<label class="label" for="input">${this.label}</label>`
          : nothing}
        <slot
          name="leading-icon"
          class="icon icon--leading"
          @slotchange=${this._onLeadingSlotChange}
        ></slot>
        <input
          id="input"
          class="input"
          type=${this.type}
          name=${this.name ?? nothing}
          .value=${this.value}
          placeholder=${isFloating ? ' ' : this.placeholder}
          ?disabled=${isDisabled}
          ?required=${this.required}
          ?readonly=${this.readonly}
          aria-invalid=${this.state === 'error' ? 'true' : nothing}
          aria-required=${this.required ? 'true' : nothing}
          aria-describedby=${this.hint ? hintId : nothing}
          @input=${this._onInput}
          @change=${this._onChange}
        />
        ${isFloating && this.label
          ? html`<label class="label" for="input">${this.label}</label>`
          : nothing}
        <slot
          name="trailing-icon"
          class="icon icon--trailing"
          @slotchange=${this._onTrailingSlotChange}
        >
          ${this._showsErrorTrailingIcon
            ? html`<span class="icon-content" aria-hidden="true"
                >${unsafeSVG(svgMap['icon-danger'])}</span
              >`
            : nothing}
        </slot>
      </div>
      ${this.hint ? html`<p id=${hintId} class="hint">${this.hint}</p>` : nothing}
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'ui-text-field': UiTextField;
  }
}
