// packages/react/src/TextInput/TextInput.tsx
import { useId, type CSSProperties, type ReactNode, type InputHTMLAttributes } from 'react';
import './text-input.css';

export type TextInputVariant = 'outline' | 'filled' | 'underlined';
export type TextInputSize = 'small' | 'default' | 'large';
export type TextInputState = 'default' | 'success' | 'error' | 'disabled';
export type TextInputLabelPlacement = 'top' | 'floating';

export interface TextInputProps
  extends Omit<InputHTMLAttributes<HTMLInputElement>, 'size' | 'onChange'> {
  variant?: TextInputVariant;
  size?: TextInputSize;
  label?: string;
  labelPlacement?: TextInputLabelPlacement;
  hint?: string;
  state?: TextInputState;
  leadingIcon?: ReactNode;
  trailingIcon?: ReactNode;
  onChange?: (value: string) => void;
  className?: string;
  style?: CSSProperties;
}

export function TextInput({
  variant = 'outline',
  size = 'default',
  label,
  labelPlacement = 'top',
  placeholder = '',
  value = '',
  hint,
  state = 'default',
  leadingIcon,
  trailingIcon,
  onChange,
  name,
  type = 'text',
  disabled,
  required,
  readOnly,
  className,
  style,
  ...inputProps
}: TextInputProps) {
  const generatedId = useId();
  const inputId = inputProps.id ?? generatedId;
  const hintId = `${inputId}-hint`;

  const isDisabled = disabled || state === 'disabled';

  const effectivePlacement = (): TextInputLabelPlacement => {
    if (variant === 'filled') return 'top';
    if (variant === 'underlined') return 'floating';
    return labelPlacement;
  };

  const isFloating = effectivePlacement() === 'floating';

  const rootClass = [
    'ui-text-input',
    `ui-text-input--${variant}`,
    size !== 'default' && `ui-text-input--${size}`,
    isFloating && 'ui-text-input--floating',
    state !== 'default' && `ui-text-input--state-${state}`,
    leadingIcon && 'ui-text-input--has-leading-icon',
    trailingIcon && 'ui-text-input--has-trailing-icon',
    className,
  ]
    .filter(Boolean)
    .join(' ');

  const labelEl = label ? (
    <label className="ui-text-input__label" htmlFor={inputId}>
      {label}
    </label>
  ) : null;

  return (
    <div className={rootClass} style={style}>
      {!isFloating && labelEl}
      <div className="ui-text-input__field-wrapper">
        {leadingIcon && (
          <span className="ui-text-input__icon ui-text-input__icon--leading">{leadingIcon}</span>
        )}
        <input
          {...inputProps}
          id={inputId}
          className="ui-text-input__input"
          type={type}
          name={name}
          value={value}
          placeholder={isFloating ? ' ' : placeholder}
          disabled={isDisabled}
          required={required}
          readOnly={readOnly}
          aria-invalid={state === 'error' ? 'true' : undefined}
          aria-required={required ? 'true' : undefined}
          aria-describedby={hint ? hintId : undefined}
          onChange={(e) => onChange?.(e.target.value)}
        />
        {isFloating && labelEl}
        {trailingIcon && (
          <span className="ui-text-input__icon ui-text-input__icon--trailing">{trailingIcon}</span>
        )}
      </div>
      {hint && (
        <p id={hintId} className="ui-text-input__hint">
          {hint}
        </p>
      )}
    </div>
  );
}

// packages/web-components/src/text-input/text-input.ts
import { LitElement, html, nothing } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { textInputStyles } from './text-input.styles.js';
import { motionStyles } from '../styles/motion.styles.js';
import { resetStyles } from '../styles/reset.styles.js';

export type TextInputVariant = 'outline' | 'filled' | 'underlined';
export type TextInputSize = 'small' | 'default' | 'large';
export type TextInputState = 'default' | 'success' | 'error' | 'disabled';
export type TextInputLabelPlacement = 'top' | 'floating';

@customElement('ui-text-input')
export class UiTextInput extends LitElement {
  static override shadowRootOptions = { ...LitElement.shadowRootOptions, delegatesFocus: true };
  static override styles = [resetStyles, motionStyles, textInputStyles];

  @property({ type: String, reflect: true }) variant: TextInputVariant = 'outline';
  @property({ type: String, reflect: true, attribute: 'data-size' }) size: TextInputSize =
    'default';
  @property({ type: String, reflect: true }) label?: string;
  @property({ type: String, reflect: true, attribute: 'label-placement' })
  labelPlacement: TextInputLabelPlacement = 'top';
  @property({ type: String, reflect: true }) placeholder = '';
  @property({ type: String, reflect: true }) value = '';
  @property({ type: String, reflect: true }) hint?: string;
  @property({ type: String, reflect: true }) state: TextInputState = 'default';
  @property({ type: String }) name?: string;
  @property({ type: String }) type: 'text' | 'email' | 'tel' | 'url' = 'text';
  @property({ type: Boolean, reflect: true }) disabled = false;
  @property({ type: Boolean, reflect: true }) required = false;
  @property({ type: Boolean, reflect: true }) readonly = false;

  private get _isFloating(): boolean {
    if (this.variant === 'filled') return false;
    if (this.variant === 'underlined') return true;
    return this.labelPlacement === 'floating';
  }

  private get _isDisabled(): boolean {
    return this.disabled || this.state === 'disabled';
  }

  private _onLeadingSlotChange(e: Event) {
    const slot = e.target as HTMLSlotElement;
    this.toggleAttribute('has-leading-icon', slot.assignedElements().length > 0);
  }

  private _onTrailingSlotChange(e: Event) {
    const slot = e.target as HTMLSlotElement;
    this.toggleAttribute('has-trailing-icon', slot.assignedElements().length > 0);
  }

  private _onInput(e: Event) {
    const input = e.target as HTMLInputElement;
    this.value = input.value;
    this.dispatchEvent(
      new CustomEvent('ui-input', { detail: { value: this.value }, bubbles: true, composed: true }),
    );
  }

  private _onChange(e: Event) {
    const input = e.target as HTMLInputElement;
    this.value = input.value;
    this.dispatchEvent(
      new CustomEvent('ui-change', {
        detail: { value: this.value },
        bubbles: true,
        composed: true,
      }),
    );
  }

  override render() {
    const isFloating = this._isFloating;
    const isDisabled = this._isDisabled;
    const hintId = 'hint';

    return html`
      ${!isFloating && this.label
        ? html`<label class="label" for="input">${this.label}</label>`
        : nothing}
      <div class="field-wrapper">
        <slot
          name="leading-icon"
          class="icon icon--leading"
          @slotchange=${this._onLeadingSlotChange}
        ></slot>
        <input
          id="input"
          class="input"
          type=${this.type}
          name=${this.name ?? nothing}
          .value=${this.value}
          placeholder=${isFloating ? ' ' : this.placeholder}
          ?disabled=${isDisabled}
          ?required=${this.required}
          ?readonly=${this.readonly}
          aria-invalid=${this.state === 'error' ? 'true' : nothing}
          aria-required=${this.required ? 'true' : nothing}
          aria-describedby=${this.hint ? hintId : nothing}
          @input=${this._onInput}
          @change=${this._onChange}
        />
        ${isFloating && this.label
          ? html`<label class="label" for="input">${this.label}</label>`
          : nothing}
        <slot
          name="trailing-icon"
          class="icon icon--trailing"
          @slotchange=${this._onTrailingSlotChange}
        ></slot>
      </div>
      ${this.hint ? html`<p id=${hintId} class="hint">${this.hint}</p>` : nothing}
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'ui-text-input': UiTextInput;
  }
}
