// packages/web-components/src/link-button/link-button.ts
import { LitElement, html, nothing } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { type ButtonVariant, type ButtonSize } from '../button/button.js';
import { buttonStyles } from '../button/button.styles.js';
import { linkButtonStyles } from './link-button.styles.js';
import { focusStyles } from '../styles/focus.styles.js';
import { resetStyles } from '../styles/reset.styles.js';
import '../loader/loader.js';

export type { ButtonVariant as LinkButtonVariant, ButtonSize as LinkButtonSize };

/**
 * Anchor element styled as a button, for navigation that should look like an action.
 *
 * @element ui-link-button
 *
 * @example
 * ```html
 * <ui-link-button href="/pricing" variant="outline">See pricing</ui-link-button>
 * ```
 *
 * @slot - Link label content.
 * @slot icon-left - Icon inside the content area, before the label.
 * @slot icon-right - Icon inside the content area, after the label.
 * @slot leading-icon - Icon in a separated box at the leading edge; requires `has-leading-icon`.
 * @slot trailing-icon - Icon in a separated box at the trailing edge; requires `has-trailing-icon`.
 */
@customElement('ui-link-button')
export class UiLinkButton extends LitElement {
  static override shadowRootOptions = { ...LitElement.shadowRootOptions, delegatesFocus: true };
  static override styles = [resetStyles, focusStyles, buttonStyles, linkButtonStyles];

  /**
   * Visual emphasis of the button.
   * @default 'primary'
   */
  @property({ type: String, reflect: true }) variant: ButtonVariant = 'primary';

  /**
   * Overall height and typography scale.
   * @default 'default'
   */
  @property({ type: String, reflect: true, attribute: 'data-size' }) size: ButtonSize = 'default';

  /** Replaces content with a spinner and blocks navigation. */
  @property({ type: Boolean, reflect: true }) loading = false;

  /** Blocks navigation and applies disabled styling (`aria-disabled`). */
  @property({ type: Boolean, reflect: true }) disabled = false;

  /** Destination URL. */
  @property({ type: String, reflect: true }) href = '';

  /** Native anchor target; `_blank` automatically adds `rel="noopener noreferrer"`. */
  @property({ type: String, reflect: true }) target?: string;

  /** Native anchor rel; overrides the automatic `_blank` fallback. */
  @property({ type: String, reflect: true }) rel?: string;

  /** Accessible name; use when the visible label is missing or insufficient. */
  @property({ type: String }) label?: string;

  /** Reserves the leading icon box; assign content via the `leading-icon` slot. */
  @property({ type: Boolean, reflect: true, attribute: 'has-leading-icon' })
  hasLeadingIcon = false;

  /** Reserves the trailing icon box; assign content via the `trailing-icon` slot. */
  @property({ type: Boolean, reflect: true, attribute: 'has-trailing-icon' })
  hasTrailingIcon = false;

  private get computedRel(): string | undefined {
    if (this.rel !== undefined) return this.rel;
    if (this.target === '_blank') return 'noopener noreferrer';
    return undefined;
  }

  private get isInactive(): boolean {
    return this.disabled || this.loading;
  }

  private get loaderSize(): 'small' | 'default' {
    return this.size === 'large' ? 'default' : 'small';
  }

  private handleClick(e: MouseEvent) {
    if (this.isInactive) {
      e.preventDefault();
    }
  }

  override render() {
    return html`
      <a
        href=${this.href}
        target=${this.target ?? nothing}
        rel=${this.computedRel ?? nothing}
        aria-disabled=${this.isInactive ? 'true' : nothing}
        aria-busy=${this.loading ? 'true' : nothing}
        aria-label=${this.label ?? nothing}
        tabindex=${this.isInactive ? '-1' : nothing}
        @click=${this.handleClick}
      >
        ${this.hasLeadingIcon
          ? html`
              <span class="icon-box icon-box--leading">
                <slot name="leading-icon"></slot>
              </span>
              <span class="separator" aria-hidden="true"></span>
            `
          : nothing}

        <span class="content">
          ${this.loading
            ? html`<ui-loader data-size=${this.loaderSize} label="Loading"></ui-loader>`
            : html`<slot name="icon-left"></slot>`}
          <span class="label"><slot></slot></span>
          ${this.loading ? nothing : html`<slot name="icon-right"></slot>`}
        </span>

        ${this.hasTrailingIcon
          ? html`
              <span class="separator" aria-hidden="true"></span>
              <span class="icon-box icon-box--trailing">
                <slot name="trailing-icon"></slot>
              </span>
            `
          : nothing}
      </a>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'ui-link-button': UiLinkButton;
  }
}

// packages/react/src/LinkButton/LinkButton.tsx
import type { CSSProperties, ReactNode } from 'react';
import { type ButtonVariant, type ButtonSize } from '../Button/Button.js';
import { Loader } from '../Loader/Loader.js';
import './LinkButton.css';

export type { ButtonVariant as LinkButtonVariant, ButtonSize as LinkButtonSize };

/**
 * Anchor element styled as a button, for navigation that should look like an action.
 *
 * @example
 * <LinkButton href="/pricing" variant="outline" iconRight={<IconArrowRight />}>See pricing</LinkButton>
 */
export interface LinkButtonProps {
  /** Destination URL. */
  href: string;
  /** Native anchor target; `_blank` automatically adds `rel="noopener noreferrer"`. */
  target?: '_self' | '_blank' | '_parent' | '_top';
  /** Native anchor rel; overrides the automatic `_blank` fallback. */
  rel?: string;
  /**
   * Visual emphasis of the button.
   * @default 'primary'
   */
  variant?: ButtonVariant;
  /**
   * Overall height and typography scale.
   * @default 'default'
   */
  size?: ButtonSize;
  /** Replaces content with a spinner and blocks navigation. */
  loading?: boolean;
  /** Blocks navigation and applies disabled styling (`aria-disabled`). */
  disabled?: boolean;
  /** Icon rendered inside the content area, before the label. */
  iconLeft?: ReactNode;
  /** Icon rendered inside the content area, after the label. */
  iconRight?: ReactNode;
  /** Icon in a separated box at the leading edge (before the separator). */
  leadingIcon?: ReactNode;
  /** Icon in a separated box at the trailing edge (after the separator). */
  trailingIcon?: ReactNode;
  /** Link label content. */
  children?: ReactNode;
  /** Click handler; not called while disabled or loading. */
  onClick?: React.MouseEventHandler<HTMLAnchorElement>;
  /** Extra class names appended to the root element. */
  className?: string;
  /** Inline styles forwarded to the root element (positioning only — never visual styles). */
  style?: CSSProperties;
  /** Accessible name; use when the visible label is missing or insufficient. */
  'aria-label'?: string;
}

export function LinkButton({
  href,
  target,
  rel,
  variant = 'primary',
  size = 'default',
  loading = false,
  disabled = false,
  iconLeft,
  iconRight,
  leadingIcon,
  trailingIcon,
  children,
  onClick,
  className,
  style,
  'aria-label': ariaLabel,
}: LinkButtonProps) {
  const isInactive = disabled || loading;
  const loaderSize = size === 'large' ? 'default' : 'small';
  const computedRel = rel ?? (target === '_blank' ? 'noopener noreferrer' : undefined);

  function handleClick(e: React.MouseEvent<HTMLAnchorElement>) {
    if (isInactive) {
      e.preventDefault();
      return;
    }
    onClick?.(e);
  }

  return (
    <a
      href={href}
      target={target}
      rel={computedRel}
      aria-disabled={isInactive ? 'true' : undefined}
      aria-busy={loading ? 'true' : undefined}
      aria-label={ariaLabel}
      tabIndex={isInactive ? -1 : undefined}
      onClick={handleClick}
      className={[
        'ui-button',
        `ui-button--${variant}`,
        size !== 'default' && `ui-button--${size}`,
        loading && 'ui-button--loading',
        isInactive && 'ui-link-button--disabled',
        className,
      ]
        .filter(Boolean)
        .join(' ')}
      style={style}
    >
      {leadingIcon && (
        <>
          <span className="ui-button__icon-box ui-button__icon-box--leading">{leadingIcon}</span>
          <span className="ui-button__separator" aria-hidden="true" />
        </>
      )}

      <span className="ui-button__content">
        {loading ? (
          <Loader size={loaderSize} label="Loading" />
        ) : (
          iconLeft && <span className="ui-button__icon">{iconLeft}</span>
        )}
        <span className="ui-button__label">{children}</span>
        {!loading && iconRight && <span className="ui-button__icon">{iconRight}</span>}
      </span>

      {trailingIcon && (
        <>
          <span className="ui-button__separator" aria-hidden="true" />
          <span className="ui-button__icon-box ui-button__icon-box--trailing">{trailingIcon}</span>
        </>
      )}
    </a>
  );
}
